const translations = {
  SK: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Vyskúšaj zadarmo',
    hero_badge: '⚡ Fitness appka novej generácie',
    hero_h1_line1: 'Trénuj.',
    hero_h1_line2: 'Sleduj pokrok.',
    hero_h1_line3: 'Dominuj.',
    hero_subtitle: 'Prvá fitness aplikácia, ktorá ťa skutočne pozná. Sleduj pokrok, buduj návyky a dominuj na každom tréningu.',
    hero_cta1: 'Začni zadarmo',
    hero_cta2: 'Pozri ako to funguje',
    stats_sections: 'sekcií',
    stats_ranks: 'rankov',
    stats_motivation: 'motivácie',
    stats_price: 'štart',
    features_title: 'Všetko čo potrebuješ',
    features_subtitle: 'Kompletný fitness ekosystém v jednej aplikácii',
    feat1_title: 'Tréning',
    feat1_desc: 'Stovky cvikov, hotové plány a AI-generované tréningy presne pre teba.',
    feat2_title: 'Výživa',
    feat2_desc: 'Sleduj makrá, kalórie a hydratáciu. Jedz chytrejšie, nie menej.',
    feat3_title: 'Telo',
    feat3_desc: 'Merania, fotky pokroku a body composition tracker na jednom mieste.',
    feat4_title: 'Komunita',
    feat4_desc: 'Výzvy, rebríčky a challenge s priateľmi. Spolu ste silnejší.',
    feat5_title: 'AI Coach',
    feat5_desc: 'Tvoj osobný tréner 24/7. Radí, motivuje a prispôsobuje plán.',
    feat6_title: 'Gamifikácia',
    feat6_desc: 'XP, odznaky a ranky. Každý tréning ťa posúva vyššie.',
    ranks_title: 'Tvoja cesta k vrcholu',
    ranks_subtitle: '6 rankov. Každý krok ťa posúva ďalej.',
    cta_title: 'Začni svoj prvý tréning dnes',
    cta_subtitle: 'Zadarmo. Bez kreditky. Bez výhovoriek.',
    cta_button: 'Spustiť BOOOM',
    footer_about: 'O nás',
    footer_contact: 'Kontakt',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Všetky práva vyhradené.',
    footer_founder: 'Laco, zakladateľ BOOOM',
  },
  EN: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Try for free',
    hero_badge: '⚡ Next-gen fitness app',
    hero_h1_line1: 'Train.',
    hero_h1_line2: 'Track.',
    hero_h1_line3: 'Dominate.',
    hero_subtitle: 'The first fitness app that truly knows you. Track your progress, build habits and dominate every workout.',
    hero_cta1: 'Start for free',
    hero_cta2: 'See how it works',
    stats_sections: 'sections',
    stats_ranks: 'ranks',
    stats_motivation: 'motivation',
    stats_price: 'to start',
    features_title: 'Everything you need',
    features_subtitle: 'Complete fitness ecosystem in one app',
    feat1_title: 'Training',
    feat1_desc: 'Hundreds of exercises, ready-made plans and AI-generated workouts tailored for you.',
    feat2_title: 'Nutrition',
    feat2_desc: 'Track macros, calories and hydration. Eat smarter, not less.',
    feat3_title: 'Body',
    feat3_desc: 'Measurements, progress photos and body composition tracker in one place.',
    feat4_title: 'Community',
    feat4_desc: "Challenges, leaderboards and friend battles. Together you're stronger.",
    feat5_title: 'AI Coach',
    feat5_desc: 'Your personal trainer 24/7. Advises, motivates and adapts your plan.',
    feat6_title: 'Gamification',
    feat6_desc: 'XP, badges and ranks. Every workout pushes you higher.',
    ranks_title: 'Your path to the top',
    ranks_subtitle: '6 ranks. Every step pushes you further.',
    cta_title: 'Start your first workout today',
    cta_subtitle: 'Free. No credit card. No excuses.',
    cta_button: 'Launch BOOOM',
    footer_about: 'About',
    footer_contact: 'Contact',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. All rights reserved.',
    footer_founder: 'Laco, founder of BOOOM',
  },
  CS: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Vyzkoušej zdarma',
    hero_badge: '⚡ Fitness appka nové generace',
    hero_h1_line1: 'Trénuj.',
    hero_h1_line2: 'Sleduj pokrok.',
    hero_h1_line3: 'Dominuj.',
    hero_subtitle: 'První fitness aplikace, která tě skutečně zná. Sleduj pokrok, buduj návyky a dominuj na každém tréninku.',
    hero_cta1: 'Začni zdarma',
    hero_cta2: 'Podívej jak to funguje',
    stats_sections: 'sekcí',
    stats_ranks: 'ranků',
    stats_motivation: 'motivace',
    stats_price: 'start',
    features_title: 'Vše co potřebuješ',
    features_subtitle: 'Kompletní fitness ekosystém v jedné aplikaci',
    feat1_title: 'Trénink',
    feat1_desc: 'Stovky cviků, hotové plány a AI-generované tréninky přesně pro tebe.',
    feat2_title: 'Výživa',
    feat2_desc: 'Sleduj makra, kalorie a hydrataci. Jez chytřeji, ne méně.',
    feat3_title: 'Tělo',
    feat3_desc: 'Měření, fotky pokroku a body composition tracker na jednom místě.',
    feat4_title: 'Komunita',
    feat4_desc: 'Výzvy, žebříčky a challenge s přáteli. Spolu jste silnější.',
    feat5_title: 'AI Coach',
    feat5_desc: 'Tvůj osobní trenér 24/7. Radí, motivuje a přizpůsobuje plán.',
    feat6_title: 'Gamifikace',
    feat6_desc: 'XP, odznaky a ranky. Každý trénink tě posouvá výš.',
    ranks_title: 'Tvoje cesta na vrchol',
    ranks_subtitle: '6 ranků. Každý krok tě posouvá dál.',
    cta_title: 'Začni svůj první trénink dnes',
    cta_subtitle: 'Zdarma. Bez kreditky. Bez výmluv.',
    cta_button: 'Spustit BOOOM',
    footer_about: 'O nás',
    footer_contact: 'Kontakt',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Všechna práva vyhrazena.',
    footer_founder: 'Laco, zakladatel BOOOM',
  },
  PL: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Wypróbuj za darmo',
    hero_badge: '⚡ Aplikacja fitness nowej generacji',
    hero_h1_line1: 'Trenuj.',
    hero_h1_line2: 'Śledź.',
    hero_h1_line3: 'Dominuj.',
    hero_subtitle: 'Pierwsza aplikacja fitness, która naprawdę cię zna. Śledź postępy, buduj nawyki i dominuj na każdym treningu.',
    hero_cta1: 'Zacznij za darmo',
    hero_cta2: 'Zobacz jak to działa',
    stats_sections: 'sekcji',
    stats_ranks: 'rang',
    stats_motivation: 'motywacji',
    stats_price: 'start',
    features_title: 'Wszystko czego potrzebujesz',
    features_subtitle: 'Kompletny ekosystem fitness w jednej aplikacji',
    feat1_title: 'Trening',
    feat1_desc: 'Setki ćwiczeń, gotowe plany i treningi generowane przez AI dopasowane do ciebie.',
    feat2_title: 'Żywienie',
    feat2_desc: 'Śledź makro, kalorie i nawodnienie. Jedz mądrzej, nie mniej.',
    feat3_title: 'Ciało',
    feat3_desc: 'Pomiary, zdjęcia postępu i body composition tracker w jednym miejscu.',
    feat4_title: 'Społeczność',
    feat4_desc: 'Wyzwania, rankingi i rywalizacja z przyjaciółmi. Razem jesteście silniejsi.',
    feat5_title: 'AI Coach',
    feat5_desc: 'Twój osobisty trener 24/7. Doradza, motywuje i dostosowuje plan.',
    feat6_title: 'Grywalizacja',
    feat6_desc: 'XP, odznaki i rangi. Każdy trening pcha cię wyżej.',
    ranks_title: 'Twoja droga na szczyt',
    ranks_subtitle: '6 rang. Każdy krok pcha cię dalej.',
    cta_title: 'Zacznij swój pierwszy trening dziś',
    cta_subtitle: 'Za darmo. Bez karty kredytowej. Bez wymówek.',
    cta_button: 'Uruchom BOOOM',
    footer_about: 'O nas',
    footer_contact: 'Kontakt',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Wszelkie prawa zastrzeżone.',
    footer_founder: 'Laco, założyciel BOOOM',
  },
  UK: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Спробуй безкоштовно',
    hero_badge: '⚡ Фітнес-додаток нового покоління',
    hero_h1_line1: 'Тренуй.',
    hero_h1_line2: 'Стеж.',
    hero_h1_line3: 'Домінуй.',
    hero_subtitle: 'Перший фітнес-додаток, який справді тебе знає. Відстежуй прогрес, будуй звички та домінуй на кожному тренуванні.',
    hero_cta1: 'Почати безкоштовно',
    hero_cta2: 'Подивитись як це працює',
    stats_sections: 'розділів',
    stats_ranks: 'рангів',
    stats_motivation: 'мотивації',
    stats_price: 'старт',
    features_title: 'Все що тобі потрібно',
    features_subtitle: 'Повна фітнес-екосистема в одному додатку',
    feat1_title: 'Тренування',
    feat1_desc: 'Сотні вправ, готові плани та AI-генеровані тренування спеціально для тебе.',
    feat2_title: 'Харчування',
    feat2_desc: 'Відстежуй макроси, калорії та гідратацію. Їж розумніше, а не менше.',
    feat3_title: 'Тіло',
    feat3_desc: 'Виміри, фото прогресу та трекер складу тіла в одному місці.',
    feat4_title: 'Спільнота',
    feat4_desc: 'Виклики, рейтинги та змагання з друзями. Разом ви сильніші.',
    feat5_title: 'AI Тренер',
    feat5_desc: 'Твій особистий тренер 24/7. Радить, мотивує та адаптує план.',
    feat6_title: 'Гейміфікація',
    feat6_desc: 'XP, значки та ранги. Кожне тренування піднімає тебе вище.',
    ranks_title: 'Твій шлях до вершини',
    ranks_subtitle: '6 рангів. Кожен крок веде тебе далі.',
    cta_title: 'Почни своє перше тренування сьогодні',
    cta_subtitle: 'Безкоштовно. Без кредитки. Без виправдань.',
    cta_button: 'Запустити BOOOM',
    footer_about: 'Про нас',
    footer_contact: 'Контакт',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Всі права захищені.',
    footer_founder: 'Laco, засновник BOOOM',
  },
};

const pageTitles = {
  SK: 'BOOOM — Trénuj. Sleduj pokrok. Dominuj.',
  EN: 'BOOOM — Train. Track. Dominate.',
  CS: 'BOOOM — Trénuj. Sleduj pokrok. Dominuj.',
  PL: 'BOOOM — Trenuj. Śledź. Dominuj.',
  UK: 'BOOOM — Тренуй. Стеж. Домінуй.',
};

function setLanguage(lang) {
  if (!translations[lang]) return;

  const t = translations[lang];

  document.documentElement.setAttribute('lang', lang === 'UK' ? 'uk' : lang.toLowerCase());
  document.documentElement.setAttribute('data-lang', lang);

  document.querySelectorAll('[data-i18n]').forEach(function (el) {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      el.textContent = t[key];
    }
  });

  document.querySelectorAll('.lang-btn').forEach(function (btn) {
    btn.classList.toggle('active', btn.textContent.trim() === lang);
  });

  document.title = pageTitles[lang] || pageTitles['SK'];

  try {
    localStorage.setItem('booom_lang', lang);
  } catch (e) {}
}

(function () {
  var saved;
  try { saved = localStorage.getItem('booom_lang'); } catch (e) {}
  setLanguage(saved && translations[saved] ? saved : 'SK');
}());
