const translations = {
  SK: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Vyskúšaj zadarmo',
    hero_badge: '⚡ Fitness appka novej generácie',
    hero_h1_line1: 'Trénuj.',
    hero_h1_line2: 'Sleduj pokrok.',
    hero_h1_line3: 'Dominuj.',
    hero_subtitle: 'Prvá fitness aplikácia, ktorá ťa skutočne pozná. Sleduj pokrok, buduj návyky a dominuj na každom tréningu.',
    hero_cta1: 'Stiahnuť BOOOM',
    hero_cta2: 'Pozri ako to funguje',
    badge1_title: '+12%',
    badge1_sub: 'svalová hmota / 90 dní',
    badge2_title: 'Nový PR!',
    badge2_sub: 'benchpress 140 kg',
    badge3_title: 'AI Skener',
    badge3_sub: 'Postava zanalyzovaná',
    phone_cta: 'Skenovať telo',
    hps_weight_label: 'Aktuálna váha',
    hps_weight_start: 'Štart: 65 kg',
    hps_weight_now: 'Teraz: 56.3 kg',
    stats_sections: 'sekcií',
    stats_ranks: 'rankov',
    stats_motivation: 'motivácie',
    stats_price: 'štart',
    features_title: 'Všetko čo potrebuješ',
    features_subtitle: 'Kompletný fitness ekosystém v jednej aplikácii',
    features_p1_title: 'AI Skener & Telo',
    features_p1_desc: 'Odfoť sa a AI okamžite zanalyzuje zloženie tela. Merania, fotky pokroku a presný body composition tracker na jednom mieste — vidíš zmenu, ktorú váha nikdy neukáže.',
    features_p2_title: 'Tréningový plán & Hardcore Tracker',
    features_p2_desc: 'Stovky cvikov, hotové plány a AI-generované tréningy presne pre teba. Časovač, pauzy a PR sledovanie — žiadne odhady, len čísla.',
    features_p3_title: 'Inteligentná Výživa & Biohacking Macros',
    features_p3_desc: 'Sleduj kalórie, makrá a hydratáciu na úrovni biohackera. Jedz chytrejšie, nie menej — a optimalizuj výkon zvnútra.',
    features_h1_title: 'Zdravie & Krvné parametre',
    features_h1_desc: '36 krvných parametrov — štítna žľaza, hormóny, cukor, cholesterol, pečeň, vitamíny. Odfotíš výsledky z papiera a AI ich vyplní za 3 sekundy.',
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Tvoj osobný tréner online 24/7. Pozná tvoj profil, krvné hodnoty, tréningy aj výživu. Radí brutálne úprimne a prispôsobuje plán za teba.',
    features_h3_title: 'Komunita & Motivation Feed',
    features_h3_desc: 'Výzvy, rebríčky a feed plný progresu komunity. XP, odznaky a 6 rankov ťa posúvajú bližšie k titulu BOOOM Monster.',
    show_more_features_cta: 'Chceš vedieť, čo vie BOOOM viac?',
    features_modal_title: 'Ešte viac BOOOM funkcií',
    features_modal_close: 'Zavrieť',
    ranks_title: 'Tvoja cesta k vrcholu',
    ranks_subtitle: '6 rankov. Každý krok ťa posúva ďalej.',
    cta_title: 'Začni svoj prvý tréning dnes',
    cta_subtitle: 'Zadarmo. Bez kreditky. Bez výhovoriek.',
    cta_button: 'Spustiť BOOOM',
    footer_about: 'O nás',
    footer_contact: 'Kontakt',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Všetky práva vyhradené.',
    footer_founder: 'Laco, zakladateľ BOOOM',
  },
  EN: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Try for free',
    hero_badge: '⚡ Next-gen fitness app',
    hero_h1_line1: 'Train.',
    hero_h1_line2: 'Track.',
    hero_h1_line3: 'Dominate.',
    hero_subtitle: 'The first fitness app that truly knows you. Track your progress, build habits and dominate every workout.',
    hero_cta1: 'Start for free',
    hero_cta2: 'See how it works',
    badge1_title: '+12%',
    badge1_sub: 'muscle mass / 90 days',
    badge2_title: 'New PR!',
    badge2_sub: 'bench press 140 kg',
    badge3_title: 'AI Scanner',
    badge3_sub: 'Body analyzed',
    phone_cta: 'Scan body',
    hps_weight_label: 'Current weight',
    hps_weight_start: 'Start: 65 kg',
    hps_weight_now: 'Now: 56.3 kg',
    stats_sections: 'sections',
    stats_ranks: 'ranks',
    stats_motivation: 'motivation',
    stats_price: 'to start',
    features_title: 'Everything you need',
    features_subtitle: 'Complete fitness ecosystem in one app',
    features_p1_title: 'AI Scanner & Body',
    features_p1_desc: 'Snap a photo and AI instantly analyzes your body composition. Measurements, progress photos and a precise body composition tracker in one place — see the change the scale never shows.',
    features_p2_title: 'Training Plans & Hardcore Tracker',
    features_p2_desc: 'Hundreds of exercises, ready-made plans and AI-generated workouts built just for you. Timer, rest periods and PR tracking — no guessing, just numbers.',
    features_p3_title: 'Smart Nutrition & Biohacking Macros',
    features_p3_desc: 'Track calories, macros and hydration at a biohacker level. Eat smarter, not less — and optimize performance from the inside.',
    features_h1_title: 'Health & Blood Markers',
    features_h1_desc: '36 blood markers — thyroid, hormones, sugar, cholesterol, liver, vitamins. Snap a photo of your paper results and AI fills them in within 3 seconds.',
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Your personal trainer online 24/7. Knows your profile, blood values, workouts and nutrition. Gives brutally honest advice and adapts your plan for you.',
    features_h3_title: 'Community & Motivation Feed',
    features_h3_desc: 'Challenges, leaderboards and a feed full of community progress. XP, badges and 6 ranks push you closer to the BOOOM Monster title.',
    show_more_features_cta: 'Want to know what else BOOOM can do?',
    features_modal_title: 'Even more BOOOM features',
    features_modal_close: 'Close',
    ranks_title: 'Your path to the top',
    ranks_subtitle: '6 ranks. Every step pushes you further.',
    cta_title: 'Start your first workout today',
    cta_subtitle: 'Free. No credit card. No excuses.',
    cta_button: 'Launch BOOOM',
    footer_about: 'About',
    footer_contact: 'Contact',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. All rights reserved.',
    footer_founder: 'Laco, founder of BOOOM',
  },
  CS: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Vyzkoušej zdarma',
    hero_badge: '⚡ Fitness appka nové generace',
    hero_h1_line1: 'Trénuj.',
    hero_h1_line2: 'Sleduj pokrok.',
    hero_h1_line3: 'Dominuj.',
    hero_subtitle: 'První fitness aplikace, která tě skutečně zná. Sleduj pokrok, buduj návyky a dominuj na každém tréninku.',
    hero_cta1: 'Začni zdarma',
    hero_cta2: 'Podívej jak to funguje',
    badge1_title: '+12%',
    badge1_sub: 'svalová hmota / 90 dní',
    badge2_title: 'Nové PR!',
    badge2_sub: 'benchpress 140 kg',
    badge3_title: 'AI skener',
    badge3_sub: 'Postava analyzována',
    phone_cta: 'Skenovat tělo',
    hps_weight_label: 'Aktuální váha',
    hps_weight_start: 'Start: 65 kg',
    hps_weight_now: 'Teď: 56.3 kg',
    stats_sections: 'sekcí',
    stats_ranks: 'ranků',
    stats_motivation: 'motivace',
    stats_price: 'start',
    features_title: 'Vše co potřebuješ',
    features_subtitle: 'Kompletní fitness ekosystém v jedné aplikaci',
    features_p1_title: 'AI Skener & Tělo',
    features_p1_desc: 'Vyfoť se a AI okamžitě zanalyzuje složení těla. Měření, fotky pokroku a přesný body composition tracker na jednom místě — vidíš změnu, kterou váha nikdy neukáže.',
    features_p2_title: 'Tréninkový plán & Hardcore Tracker',
    features_p2_desc: 'Stovky cviků, hotové plány a AI-generované tréninky přesně pro tebe. Časovač, pauzy a sledování PR — žádné odhady, jen čísla.',
    features_p3_title: 'Chytrá výživa & Biohacking Makra',
    features_p3_desc: 'Sleduj kalorie, makra a hydrataci na úrovni biohackera. Jez chytřeji, ne méně — a optimalizuj výkon zevnitř.',
    features_h1_title: 'Zdraví & Krevní parametry',
    features_h1_desc: '36 krevních parametrů — štítná žláza, hormony, cukr, cholesterol, játra, vitamíny. Vyfotíš výsledky z papíru a AI je vyplní za 3 sekundy.',
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Tvůj osobní trenér online 24/7. Zná tvůj profil, krevní hodnoty, tréninky i výživu. Radí brutálně upřímně a přizpůsobuje plán za tebe.',
    features_h3_title: 'Komunita & Motivation Feed',
    features_h3_desc: 'Výzvy, žebříčky a feed plný progresu komunity. XP, odznaky a 6 ranků tě posouvají blíž k titulu BOOOM Monster.',
    show_more_features_cta: 'Chceš vědět, co BOOOM umí ještě víc?',
    features_modal_title: 'Ještě víc BOOOM funkcí',
    features_modal_close: 'Zavřít',
    ranks_title: 'Tvoje cesta na vrchol',
    ranks_subtitle: '6 ranků. Každý krok tě posouvá dál.',
    cta_title: 'Začni svůj první trénink dnes',
    cta_subtitle: 'Zdarma. Bez kreditky. Bez výmluv.',
    cta_button: 'Spustit BOOOM',
    footer_about: 'O nás',
    footer_contact: 'Kontakt',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Všechna práva vyhrazena.',
    footer_founder: 'Laco, zakladatel BOOOM',
  },
  PL: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Wypróbuj za darmo',
    hero_badge: '⚡ Aplikacja fitness nowej generacji',
    hero_h1_line1: 'Trenuj.',
    hero_h1_line2: 'Śledź.',
    hero_h1_line3: 'Dominuj.',
    hero_subtitle: 'Pierwsza aplikacja fitness, która naprawdę cię zna. Śledź postępy, buduj nawyki i dominuj na każdym treningu.',
    hero_cta1: 'Zacznij za darmo',
    hero_cta2: 'Zobacz jak to działa',
    badge1_title: '+12%',
    badge1_sub: 'masa mięśniowa / 90 dni',
    badge2_title: 'Nowy PR!',
    badge2_sub: 'wyciskanie 140 kg',
    badge3_title: 'Skaner AI',
    badge3_sub: 'Ciało przeanalizowane',
    phone_cta: 'Skanuj ciało',
    hps_weight_label: 'Aktualna waga',
    hps_weight_start: 'Start: 65 kg',
    hps_weight_now: 'Teraz: 56.3 kg',
    stats_sections: 'sekcji',
    stats_ranks: 'rang',
    stats_motivation: 'motywacji',
    stats_price: 'start',
    features_title: 'Wszystko czego potrzebujesz',
    features_subtitle: 'Kompletny ekosystem fitness w jednej aplikacji',
    features_p1_title: 'AI Skaner & Ciało',
    features_p1_desc: 'Zrób zdjęcie i AI natychmiast przeanalizuje skład twojego ciała. Pomiary, zdjęcia postępu i precyzyjny body composition tracker w jednym miejscu — zobacz zmianę, której waga nigdy nie pokaże.',
    features_p2_title: 'Plan treningowy & Hardcore Tracker',
    features_p2_desc: 'Setki ćwiczeń, gotowe plany i treningi generowane przez AI stworzone właśnie dla ciebie. Timer, przerwy i śledzenie PR — żadnych domysłów, tylko liczby.',
    features_p3_title: 'Inteligentne żywienie & Biohacking Macros',
    features_p3_desc: 'Śledź kalorie, makro i nawodnienie na poziomie biohackera. Jedz mądrzej, nie mniej — i optymalizuj wydajność od wewnątrz.',
    features_h1_title: 'Zdrowie & Parametry krwi',
    features_h1_desc: '36 parametrów krwi — tarczyca, hormony, cukier, cholesterol, wątroba, witaminy. Zrób zdjęcie wyników z papieru, a AI uzupełni je w 3 sekundy.',
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Twój osobisty trener online 24/7. Zna twój profil, wyniki krwi, treningi i dietę. Radzi brutalnie szczerze i dopasowuje plan za ciebie.',
    features_h3_title: 'Społeczność & Motivation Feed',
    features_h3_desc: 'Wyzwania, rankingi i feed pełen postępów społeczności. XP, odznaki i 6 rang przybliżają cię do tytułu BOOOM Monster.',
    show_more_features_cta: 'Chcesz wiedzieć, co jeszcze umie BOOOM?',
    features_modal_title: 'Jeszcze więcej funkcji BOOOM',
    features_modal_close: 'Zamknij',
    ranks_title: 'Twoja droga na szczyt',
    ranks_subtitle: '6 rang. Każdy krok pcha cię dalej.',
    cta_title: 'Zacznij swój pierwszy trening dziś',
    cta_subtitle: 'Za darmo. Bez karty kredytowej. Bez wymówek.',
    cta_button: 'Uruchom BOOOM',
    footer_about: 'O nas',
    footer_contact: 'Kontakt',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Wszelkie prawa zastrzeżone.',
    footer_founder: 'Laco, założyciel BOOOM',
  },
  UK: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Спробуй безкоштовно',
    hero_badge: '⚡ Фітнес-додаток нового покоління',
    hero_h1_line1: 'Тренуй.',
    hero_h1_line2: 'Стеж.',
    hero_h1_line3: 'Домінуй.',
    hero_subtitle: 'Перший фітнес-додаток, який справді тебе знає. Відстежуй прогрес, будуй звички та домінуй на кожному тренуванні.',
    hero_cta1: 'Почати безкоштовно',
    hero_cta2: 'Подивитись як це працює',
    badge1_title: '+12%',
    badge1_sub: "м'язова маса / 90 днів",
    badge2_title: 'Новий PR!',
    badge2_sub: 'жим лежачи 140 кг',
    badge3_title: 'AI Сканер',
    badge3_sub: 'Тіло проаналізовано',
    phone_cta: 'Скан тіла',
    hps_weight_label: 'Поточна вага',
    hps_weight_start: 'Старт: 65 кг',
    hps_weight_now: 'Зараз: 56.3 кг',
    stats_sections: 'розділів',
    stats_ranks: 'рангів',
    stats_motivation: 'мотивації',
    stats_price: 'старт',
    features_title: 'Все що тобі потрібно',
    features_subtitle: 'Повна фітнес-екосистема в одному додатку',
    features_p1_title: 'AI Сканер & Тіло',
    features_p1_desc: 'Сфотографуйся, і AI миттєво проаналізує склад твого тіла. Виміри, фото прогресу та точний трекер складу тіла в одному місці — побач зміну, яку вага ніколи не покаже.',
    features_p2_title: 'Тренувальний план & Hardcore Tracker',
    features_p2_desc: 'Сотні вправ, готові плани та AI-генеровані тренування саме для тебе. Таймер, паузи та відстеження PR — жодних припущень, лише цифри.',
    features_p3_title: 'Розумне харчування & Biohacking Macros',
    features_p3_desc: 'Стеж за калоріями, макросами та гідратацією на рівні біохакера. Їж розумніше, а не менше — і оптимізуй продуктивність зсередини.',
    features_h1_title: "Здоров'я & Показники крові",
    features_h1_desc: "36 показників крові — щитоподібна залоза, гормони, цукор, холестерин, печінка, вітаміни. Сфотографуй результати з паперу, і AI заповнить їх за 3 секунди.",
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Твій особистий тренер онлайн 24/7. Знає твій профіль, показники крові, тренування та харчування. Радить максимально чесно і підлаштовує план за тебе.',
    features_h3_title: 'Спільнота & Motivation Feed',
    features_h3_desc: 'Виклики, рейтинги та стрічка прогресу спільноти. XP, значки та 6 рангів наближають тебе до титулу BOOOM Monster.',
    show_more_features_cta: 'Хочеш дізнатись, що ще вміє BOOOM?',
    features_modal_title: 'Ще більше функцій BOOOM',
    features_modal_close: 'Закрити',
    ranks_title: 'Твій шлях до вершини',
    ranks_subtitle: '6 рангів. Кожен крок веде тебе далі.',
    cta_title: 'Почни своє перше тренування сьогодні',
    cta_subtitle: 'Безкоштовно. Без кредитки. Без виправдань.',
    cta_button: 'Запустити BOOOM',
    footer_about: 'Про нас',
    footer_contact: 'Контакт',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Всі права захищені.',
    footer_founder: 'Laco, засновник BOOOM',
  },
};

const pageTitles = {
  SK: 'BOOOM — Trénuj. Sleduj pokrok. Dominuj.',
  EN: 'BOOOM — Train. Track. Dominate.',
  CS: 'BOOOM — Trénuj. Sleduj pokrok. Dominuj.',
  PL: 'BOOOM — Trenuj. Śledź. Dominuj.',
  UK: 'BOOOM — Тренуй. Стеж. Домінуй.',
};

function setLanguage(lang) {
  if (!translations[lang]) return;

  const t = translations[lang];

  document.documentElement.setAttribute('lang', lang === 'UK' ? 'uk' : lang.toLowerCase());
  document.documentElement.setAttribute('data-lang', lang);

  document.querySelectorAll('[data-i18n]').forEach(function (el) {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      el.textContent = t[key];
    }
  });

  document.querySelectorAll('[data-i18n-aria]').forEach(function (el) {
    const key = el.getAttribute('data-i18n-aria');
    if (t[key] !== undefined) {
      el.setAttribute('aria-label', t[key]);
    }
  });

  document.querySelectorAll('.lang-btn').forEach(function (btn) {
    btn.classList.toggle('active', btn.textContent.trim() === lang);
  });

  document.title = pageTitles[lang] || pageTitles['SK'];

  try {
    localStorage.setItem('booom_lang', lang);
  } catch (e) {}
}

(function () {
  var saved;
  try { saved = localStorage.getItem('booom_lang'); } catch (e) {}
  setLanguage(saved && translations[saved] ? saved : 'SK');
}());
