const translations = {
  SK: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Vyskúšaj zadarmo',
    hero_badge: '⚡ Fitness appka novej generácie',
    hero_h1_line1: 'Trénuj.',
    hero_h1_line2: 'Sleduj pokrok.',
    hero_h1_line3: 'Dominuj.',
    hero_subtitle: 'Prvá fitness aplikácia, ktorá ťa skutočne pozná. Sleduj pokrok, buduj návyky a dominuj na každom tréningu.',
    hero_cta1: 'Stiahnuť BOOOM',
    hero_cta2: 'Pozri ako to funguje',
    badge1_title: '+12%',
    badge1_sub: 'svalová hmota / 90 dní',
    badge2_title: 'Nový PR!',
    badge2_sub: 'benchpress 140 kg',
    badge3_title: 'AI Skener',
    badge3_sub: 'Postava zanalyzovaná',
    phone_cta: 'Skenovať telo',
    hps_weight_label: 'Aktuálna váha',
    hps_weight_start: 'Štart: 65 kg',
    hps_weight_now: 'Teraz: 56.3 kg',
    fp_weight_label: 'Telesná váha',
    fp_weight_before: 'Predtým: 79 kg',
    fp_weight_after: 'Teraz: 68.4 kg',
    fp_timer_label: 'Aktuálny cvik',
    fp_timer_set1: 'Séria 1 — 80 kg × 8',
    fp_timer_set2: 'Séria 2 — 85 kg × 6',
    fp_timer_set3: 'Séria 3 — 90 kg × 5',
    fp_timer_cta: 'Dokončiť sériu',
    fp_macro_label: 'Dnešný príjem',
    fp_blood_label: 'Krvné hodnoty',
    fp_blood_chol: 'Cholesterol — vysoký',
    fp_blood_vitd: 'Vitamín D — v norme',
    fp_supp_label: 'Dnešné suplementy',
    fp_supp_creatine: 'Kreatín — 5 g',
    fp_supp_protein: 'Whey — 30 g',
    fp_supp_omega: 'Omega-3 — 2 g',
    fp_supp_vitd: 'Vit. D — 4000 IU',
    fp_cardio_label: 'Beh — zóna 3',
    fp_cardio_pace: 'Tempo 5:12/km',
    fp_cardio_hr: 'Tep 158 bpm',
    stats_sections: 'sekcií',
    stats_ranks: 'rankov',
    stats_motivation: 'motivácie',
    stats_price: 'štart',
    features_title: 'Všetko čo potrebuješ',
    features_subtitle: 'Kompletný fitness ekosystém v jednej aplikácii',
    features_p1_title: 'AI Skener & Telo',
    features_p1_desc: 'Odfoť sa a AI okamžite zanalyzuje zloženie tela. Merania, fotky pokroku a presný body composition tracker na jednom mieste — vidíš zmenu, ktorú váha nikdy neukáže.',
    features_p2_title: 'Tréningový plán & Hardcore Tracker',
    features_p2_desc: 'Stovky cvikov, hotové plány a AI-generované tréningy presne pre teba. Časovač, pauzy a PR sledovanie — žiadne odhady, len čísla.',
    features_p3_title: 'Inteligentná Výživa & Biohacking Macros',
    features_p3_desc: 'Sleduj kalórie, makrá a hydratáciu na úrovni biohackera. Jedz chytrejšie, nie menej — a optimalizuj výkon zvnútra.',
    features_h1_title: 'Zdravie & Krvné parametre',
    features_h1_desc: '36 krvných parametrov — štítna žľaza, hormóny, cukor, cholesterol, pečeň, vitamíny. Odfotíš výsledky z papiera a AI ich vyplní za 3 sekundy.',
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Tvoj osobný tréner online 24/7. Pozná tvoj profil, krvné hodnoty, tréningy aj výživu. Radí brutálne úprimne a prispôsobuje plán za teba.',
    features_h3_title: 'Komunita & Motivation Feed',
    features_h3_desc: 'Výzvy, rebríčky a feed plný progresu komunity. XP, odznaky a 6 rankov ťa posúvajú bližšie k titulu BOOOM Monster.',
    show_more_features_cta: 'Chceš vedieť, čo vie BOOOM viac?',
    features_modal_title: 'Ešte viac BOOOM funkcií',
    features_modal_close: 'Zavrieť',
    ranks_title: 'Tvoja cesta k vrcholu',
    ranks_subtitle: '6 rankov. Každý krok ťa posúva ďalej.',
    cta_title: 'Začni svoj prvý tréning dnes',
    cta_subtitle: 'Zadarmo. Bez kreditky. Bez výhovoriek.',
    cta_button: 'Spustiť BOOOM',
    footer_about: 'O nás',
    footer_contact: 'Kontakt',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Všetky práva vyhradené.',
    footer_founder: 'Laco, zakladateľ BOOOM',
    footer_home: 'Domov',
    // Navigation
    nav_enhanced_fitness: 'Za hranicou naturalu',
    // LAB Teaser
    lab_badge: 'RESTRICTED ACCESS',
    lab_teaser_title: 'BOOOM LAB: Za hranicou naturalu',
    lab_teaser_desc: 'Testosterón. Trenbolon. Anavar. Dianabol. Brutálne úprimný deep-dive do sveta enhanced fitness — mechanizmy, vedľajšie účinky, krvné markery a psychologická realita.',
    lab_teaser_cta: 'Vstúpiť do zakázanej zóny',
    lab_teaser_disclaimer: '⚠️ Len pre vzdelávacie účely. BOOOM nepodporuje ani nepropaguje používanie anabolických steroidov.',
    // LAB Page
    nav_back: 'Späť na hlavnú',
    lab_hero_badge: 'VZDELÁVACÍ OBSAH',
    lab_hero_title: 'BOOOM LAB: Za hranicou naturalu',
    lab_hero_desc: 'Brutálne úprimný deep-dive do sveta enhanced fitness. Bez romantizácie, bez moralizovania — len fakty, mechanizmy, vedľajšie účinky a čísla, ktoré musíš sledovať, ak si sa rozhodol ísť touto cestou.',
    lab_disclaimer_title: '⚠️ DÔLEŽITÉ UPOZORNENIE:',
    lab_disclaimer_text: 'Tento obsah je určený čisto na vzdelávacie účely. BOOOM nepodporuje, nepropaguje ani nevyzýva k používaniu anabolických steroidov. Akékoľvek rozhodnutia týkajúce sa zdravia a suplementácie by mali byť konzultované s kvalifikovaným lekárom.',
    // Substances
    substances_tag: 'HLAVNÉ LÁTKY',
    substances_title: 'Veľká štvorka: Čo potrebuješ vedieť',
    substances_subtitle: 'Mechanizmy účinku, dávkovanie, vedľajšie efekty a detekcia',
    tst_title: 'Testosterón (TST)',
    tst_intro: 'Základ každého cyklu. Prirodzený androgénny hormón, ktorý tvoje telo vyrába. Enhanced verzii ho pridávajú exogénne v dávkach 5-10× vyšších ako prirodzená produkcia.',
    tst_mechanism: 'Ako funguje',
    tst_m1: 'Zvyšuje syntézu bielkovín v svalových bunkách',
    tst_m2: 'Potláča katabolizmus (rozklad svalov)',
    tst_m3: 'Zvyšuje retenciu dusíka a zadržiavanie vody',
    tst_m4: 'Stimuluje erytropoézu (tvorbu červených krviniek)',
    tst_sides: 'Vedľajšie účinky',
    tst_s1: 'Aromatizácia: konverzia na estrogén → gynekomastia, zadržiavanie vody',
    tst_s2: 'Potlačenie prirodzenej produkcie: LH/FSH klesá na nulu',
    tst_s3: 'Kardiovaskulárne: zvýšený hematokrit, nárast krvného tlaku',
    tst_s4: 'Akné, plešatosť (ak si geneticky predisponovaný)',
    tst_doses: 'Typické dávky',
    tst_doses_text: '250-500 mg/týždeň (beginners), 500-750 mg/týždeň (intermediate), 750+ mg/týždeň (advanced risk zone)',
    tren_title: 'Trenbolon (TREN)',
    tren_intro: '"Najsilnejší steroid na planéte." Pôvodne určený pre dobytok. Extrémne anabolický aj androgénny. Dáva obrovské gainy, ale platíš za to tvrdou cenou.',
    tren_mechanism: 'Ako funguje',
    tren_m1: '5× anabolickejší ako testosterón',
    tren_m2: 'Nekonvertuje na estrogén, ale viaže sa na progesterónové receptory',
    tren_m3: 'Dramaticky zvyšuje IGF-1 (inzulínu podobný rastový faktor)',
    tren_m4: 'Inhibuje kortizol (stresový hormón)',
    tren_sides: 'Vedľajšie účinky',
    tren_s1: 'Nočné potenie, insomnia: brutálne narušený spánok',
    tren_s2: '"Tren cough": záchvaty kašľa po injekcii',
    tren_s3: 'Kardio dystopia: extrémne zhoršená vytrvalosť',
    tren_s4: 'Agresivita, úzkosť, paranoja ("Tren rage")',
    tren_s5: 'Potlačenie libida post-cycle (môže trvať mesiace)',
    tren_doses: 'Typické dávky',
    tren_doses_text: '200-400 mg/týždeň (acetát form), 400-600 mg/týždeň (enanthate). Beginners by sa mali držať ďaleko.',
    var_title: 'Anavar (Oxandrolone)',
    var_intro: '"Ženský steroid." Mierny, ale čistý. Nepridáva veľké gainy, ale dáva suchú, kvalitnú svalovinu. Obľúbený v cutting fázach.',
    var_mechanism: 'Ako funguje',
    var_m1: 'Orálny steroid, DHT derivát',
    var_m2: 'Nízky androgénny efekt, minimálna aromatizácia',
    var_m3: 'Zvyšuje silu bez výrazného nárastu hmotnosti',
    var_m4: 'Podporuje spalovanie tukov a vaskulárnosť',
    var_sides: 'Vedľajšie účinky',
    var_s1: 'Hepatotoxicita: zaťaženie pečene (AST/ALT ↑)',
    var_s2: 'Lipidový profil: pokles HDL, nárast LDL',
    var_s3: 'Potlačenie prirodzeného TST (miernejšie ako injekcie)',
    var_s4: 'Relatívne "bezpečný" v porovnaní s inou oráliou, ale stále nie candy',
    var_doses: 'Typické dávky',
    var_doses_text: '20-50 mg/deň (ženy), 50-80 mg/deň (muži), drahý ako čert — často falšovaný',
    dbol_title: 'Dianabol (Methandrostenolone)',
    dbol_intro: '"Dbol" — legenda zlatej éry bodybuildingu. Masívne gainy za krátky čas, ale veľká časť je voda. Kickstarter prvých 4-6 týždňov cyklu.',
    dbol_mechanism: 'Ako funguje',
    dbol_m1: 'Silná anabolická aj androgénna aktivita',
    dbol_m2: 'Výrazná aromatizácia na estrogén',
    dbol_m3: 'Rýchly nárast sily a hmotnosti (5-10 kg za 4 týždne)',
    dbol_m4: 'Zvyšuje glykogenolýzu a syntézu bielkovín',
    dbol_sides: 'Vedľajšie účinky',
    dbol_s1: 'Masívna zadržiavanie vody: "moon face", edémy',
    dbol_s2: 'Gynekomastia risk: vysoká estrogénová aktivita',
    dbol_s3: 'Hepatotoxicita: pečeň trpí (17-alpha alkylovaný)',
    dbol_s4: 'Krvný tlak: značný nárast',
    dbol_s5: 'Akné, mastná koža',
    dbol_doses: 'Typické dávky',
    dbol_doses_text: '20-40 mg/deň (beginners), 40-60 mg/deň (advanced). Lacný, ale brutal na pečeň.',
    // Blood Markers
    markers_tag: 'ZDRAVOTNÉ MARKERY',
    markers_title: '36 krvných parametrov, ktoré musíš sledovať',
    markers_subtitle: 'Bez monitorovania = ruská ruleta s tvojím telom',
    markers_intro: 'Ak bereš PEDs a nemonitoruješ krvné hodnoty, hráš sa s ohňom. Tu sú kľúčové markery, ktoré BOOOM trackuje, a prečo sú kritické.',
    marker_ast_alt: 'AST / ALT',
    marker_ast_alt_desc: 'Pečeňové enzýmy. Ak sú elevated, tvoja pečeň kričí o pomoc. Všetky orálne steroidy (Anavar, Dbol) ich vystreľujú nahor.',
    marker_hdl_ldl: 'HDL / LDL',
    marker_hdl_ldl_desc: 'Cholesterol. PEDs brutálne potláčajú HDL (dobrý) a zvyšujú LDL (zlý). Riziko infarktu a mŕtvice exponenciálne rastie.',
    marker_hematocrit: 'Hematokrit',
    marker_hematocrit_desc: '% červených krviniek v krvi. Testosterón ho zvyšuje. Ak ide nad 54 %, krv je ako sirup → tromby, mozgová príhoda.',
    marker_lh_fsh: 'LH / FSH',
    marker_lh_fsh_desc: 'Hormóny hypofýzy riadiace produkciu TST a spermií. Na cycle padajú na nulu. Ak sa nevrátia post-cycle = si hypogonadálny.',
    marker_e2: 'Estradiol (E2)',
    marker_e2_desc: 'Estrogén. Ak je príliš vysoký (z aromatizácie TST) → gyno, zadržiavanie vody. Ak príliš nízky (z AI overdose) → zlomené kĺby, libido v prdeli.',
    marker_prolactin: 'Prolaktín',
    marker_prolactin_desc: 'Trenbolon a Nandrolone ho zvyšujú. Vysoký prolaktín = erectile dysfunction, gynekomastia, "deca dick".',
    marker_creatinine: 'Kreatinín / GFR',
    marker_creatinine_desc: 'Funkcia obličiek. Anaboliká ich zaťažujú. Ak klesá GFR, obličky zlyhávajú. Ireverzibilné poškodenie.',
    marker_tsh: 'TSH / T3 / T4',
    marker_tsh_desc: 'Štítna žľaza. PEDs ju môžu narušiť. Ak sú mimo, metabolizmus ide do prdele, únava, depresie, prírastky končia.',
    // Charts
    chart_tst_title: 'Graf 1: Natural vs Enhanced — Hladiny testosterónu',
    chart_tst_desc: 'Porovnanie prirodzených hladín testosterónu s enhanced verziou počas aktívneho cyklu',
    chart_tst_legend_natural: 'Prirodzená produkcia (muž 20-40 rokov)',
    chart_tst_legend_enhanced: 'Enhanced cycle (500 mg TST/týždeň)',
    chart_strength_title: 'Graf 2: Strength Rollercoaster — Cyklus a crash',
    chart_strength_desc: 'Ako vyzerá sila počas cyklu a po ňom, ak nerobíš správne PCT (Post Cycle Therapy)',
    chart_strength_legend_on: 'Weeks 0-12: Exponenciálny rast sily',
    chart_strength_legend_off: 'Weeks 12-20: Katastrofický pokles bez PCT',
    // Psychology
    psych_tag: 'PSYCHOLOGICKÁ REALITA',
    psych_title: 'God Mode vs Hormonal Hell',
    psych_subtitle: 'Čo nikto nepovie: ako PEDs ovplyvňujú tvoju hlavu',
    psych_god_title: '🚀 "God Mode" (On Cycle)',
    psych_god_1: 'Neprekonateľná sebadôvera',
    psych_god_2: 'Zero úzkosti, agresivita v gyme je výhodou',
    psych_god_3: 'Libido cez strechu (ak je estrogén v norme)',
    psych_god_4: 'Extrémna motivácia, "na hovno" únava',
    psych_god_5: 'Pocit nesmrteľnosti, dominancia vo všetkom',
    psych_hell_title: '💀 "Hormonal Hell" (Post-Cycle)',
    psych_hell_1: 'Depresia, úzkosti, nulová motivácia',
    psych_hell_2: 'Libido v prdeli, erectile dysfunction',
    psych_hell_3: 'Insomnia, podráždenosť, emocionálna labilita',
    psych_hell_4: 'Strata všetkých gainsov (svalová hmota padá)',
    psych_hell_5: 'Pocit, že si zbytočný — "kto som bez roids?"',
    psych_outro: 'Pravda je brutálna: Na cycle sa cítiš ako boh. Off-cycle máš pocit, že ti zomrel pes. Mnohí sa dostávajú do závislosti práve kvôli tomuto psychologickému whiplashu. Blast & cruise (nekonečný cycle bez pauzy) sa stáva normou, lebo PCT je psychicky neúnosné.',
    // Detection
    detection_tag: 'GYM LORE',
    detection_title: 'Ako spoznáš, že niekto nie je natural?',
    detection_subtitle: 'Visual cues, ktoré nepustia — žiadne testy nepotrebné',
    detection_shoulders_title: '3D Delts (ramená)',
    detection_shoulders_desc: 'Okrúhle, nafúknuté ramená s extrémnou separáciou. Androgénne receptory v deltoch reagujú brutálne na steroidy.',
    detection_flushing_title: 'Flushing & Akné',
    detection_flushing_desc: 'Červená tvár počas tréningu, akné na chrbte a pleciach. Zvýšený tep + zvýšený hematokrit = permanentný "pump".',
    detection_gut_title: '"Roid Gut" (Palumboism)',
    detection_gut_desc: 'Nafúknuté brucho napriek nízkemu tuku. Rast vnútorných orgánov z inzulínu + HGH. Moderná bodybuilding epidémia.',
    detection_gains_title: 'Nereálne rýchle gainy',
    detection_gains_desc: 'Ak niekto za 12 týždňov naberie 15 kg svalovej hmoty a zároveň schudne — nie, nejde o kurací ryžu a brokoliciu.',
    detection_vascularity_title: 'Extrémna vaskulárnosť',
    detection_vascularity_desc: 'Žily ako hadice aj v pokoji. Nízky tuk + zadržiavanie vody v svaloch + zvýšený krvný objem = roadmap look.',
    detection_strength_title: 'Nadľudská sila pri nízkej váhe',
    detection_strength_desc: 'Benč 160 kg pri 80 kg telesnej váhe a 8 % tuku? Anavar + Tren stack. Natural limit je ďaleko nižšie.',
    // LAB CTA
    lab_cta_title: 'Sleduj svoje zdravie. Nie výhovorky.',
    // New index.html translations
    nav_features: 'Funkcie',
    nav_thyroid: 'Štítna žľaza',
    nav_diets_toggle: 'Diéty & intolerancie ▾',
    nav_diets_mobile: 'Diéty & intolerancie',
    nav_diet_lactose: '🥛 Bezlaktózová diéta',
    nav_diet_gluten: '🌾 Bezlepková diéta',
    nav_diet_histamine: '🧪 Histamínová intolerancia',
    nav_diet_hashimoto: '🧬 Hashimotova tyreoiditída',
    nav_ranks: 'Ranky',
    nav_story: 'Príbeh',
    nav_mobile_cta: 'Stiahnuť BOOOM zadarmo →',
    hero_stat1_label: 'Sekcií appky',
    hero_stat2_label: 'Krvných parametrov',
    hero_stat3_label: 'AI Coach',
    story_tag: 'Príbeh zakladateľa',
    story_btn: 'Prečo vznikol BOOOM? Môj príbeh.',
    feature_tag_ai_scan: 'AI sken',
    feature_tag_body_scan: 'Body scan',
    feature_tag_progress_pics: 'Fotky pokroku',
    feature_tag_trends: 'Trendy',
    feature_tag_exercises: 'Stovky cvikov',
    feature_tag_ai_plans: 'AI plány',
    feature_tag_pr_tracking: 'PR tracking',
    feature_tag_timer: 'Časovač',
    feature_tag_macros: 'Makrá',
    feature_tag_calories: 'Kalórie',
    feature_tag_hydration: 'Hydratácia',
    feature_tag_biohacking: 'Biohacking',
    feature_tag_36_params: '36 parametrov',
    feature_tag_time_trends: 'Trendy v čase',
    feature_tag_alerts: 'Alarmy',
    feature_tag_247: '24/7 online',
    feature_tag_personalized: 'Personalizovaný',
    feature_tag_blood_values: 'Krvné hodnoty',
    feature_tag_training_plans: 'Plány tréningov',
    feature_tag_challenges: 'Výzvy',
    feature_tag_leaderboards: 'Rebríčky',
    feature_tag_xp_ranks: 'XP & Ranky',
    feature_tag_feed: 'Feed',
    testimonials_tag: 'Komunita',
    testimonials_title: 'Čo hovoria naši makáči',
    testimonials_subtitle: 'Skutočné príbehy. Skutočný progres.',
    testimonials_rating: 'Hodnotené beta používateľmi',
    testimonial1_text: '"Konečne appka, ktorá chápe, že fitness nie je len o kalóriách. Sledovanie krvných hodnôt mi otvorilo oči — zistil som, že mám nízky feritín a to bol dôvod, prečo som stagnoval rok. BOOOM mi doslova zmenil život."',
    testimonial1_name: 'Marek Kováč',
    testimonial1_role: 'Powerlifter · Bratislava',
    testimonial2_text: '"Mám Hashimoto a pred BOOOM som vôbec nevedela, čo smiem jesť a kedy cvičiť. AI Coach mi vysvetlil súvislosti, ktoré mi žiadny tréner ani lekár nepovedal tak ľudsky. Teraz mám konečne systém."',
    testimonial2_name: 'Zuzana Horáková',
    testimonial2_role: 'Mamička & CrossFit nadšenkyňa · Žilina',
    testimonial3_text: '"Mal som 41 rokov a myslel som si, že stagnácia je vek. GPS tracking, krvné hodnoty, AI plán — za 3 mesiace som schudol 9 kg a pritom pribral svalovku. Toto nie je appka, toto je osobný tréner za cenu kávy."',
    testimonial3_name: 'Tomáš Novák',
    testimonial3_role: 'Cyklista & Otec troch detí · Košice',
    fomo_badge: 'Obmedzený Early Access',
    fomo_title: 'BOOOM nie je appka pre ľudí,<br>čo sa chodia do fitka fotiť.',
    fomo_subtitle: 'Staviame komunitu makáčov, ktorí chcú vidieť reálne čísla, nie len lajky. Prvých 500 profilov má prednostný prístup k novým funkciám navždy.',
    fomo_label: 'Aktuálne voľných profilov:',
    fomo_meta_taken: '27 profilov obsadených',
    fomo_meta_free: '473 voľných',
    fomo_cta: 'Zaregistrovať sa zadarmo →',
    diets_tag: 'Zdravie & Diéty',
    diets_title: 'Viac ako len fitness',
    diets_subtitle: 'Komplexné sprievodcovia pre ľudí so špecifickými zdravotnými potrebami',
    teaser_thyroid_title: 'Čo by si mal vedieť o štítnej žľaze',
    teaser_thyroid_desc: 'Hypotyreóza, hypertyreóza, Hashimoto — príznaky, diéta, suplementácia a najnovšie vedecké štúdie. Osobná skúsenosť zakladateľa BOOOM.',
    teaser_lactose_title: 'Bezlaktózová diéta — kompletný sprievodca',
    teaser_lactose_desc: 'Čo jesť, čo vynechať a ako nezísť o dôležité živiny. Kompletný sprievodca pre ľudí s laktózovou intoleranciou.',
    teaser_gluten_title: 'Bezlepková diéta — pre celiatikov',
    teaser_gluten_desc: 'Čo jesť, čo vylúčiť, kde sa skrýva lepok a ako nepríjsť o dôležité živiny. Kompletný sprievodca.',
    teaser_histamine_title: 'Histamínová intolerancia',
    teaser_histamine_desc: 'Bolí ťa hlava po víne? Svrbí ťa koža po syre? Možno to nie je alergia. Kompletný sprievodca histamínovou intoleranciou.',
    teaser_hashimoto_title: 'Hashimotova tyreoiditída — diéta a suplementácia',
    teaser_hashimoto_desc: 'Selén, myo-inozitol, bezlepková diéta a všetko čo veda hovorí o liečbe Hashimota stravou. Osobná skúsenosť zakladateľa BOOOM.',
    teaser_read_more: 'Čítať viac →',
    cta_tag: 'Začni dnes',
    cta_benefit1: 'Kompletný prístup zadarmo',
    cta_benefit2: 'AI Coach od prvého dňa',
    cta_benefit3: 'Bez viazanosti, zruš kedykoľvek',
    cta_note: 'Stovky ľudí z SK, CZ a PL už sledujú svoj progres.',
    hero_scroll: 'Scroll',
    features_tag: 'Funkcie',
    lab_cta_desc: 'Či už si natural, enhanced, alebo len zvedavý — BOOOM ti dáva komplexný monitoring 36 krvných parametrov, tréningov, výživy a tvojho pokroku. Vidíš čísla. Rozumieš telu. Dominuješ.',
    lab_cta_button: 'Stiahnuť BOOOM zadarmo',
  },
  EN: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Try for free',
    hero_badge: '⚡ Next-gen fitness app',
    hero_h1_line1: 'Train.',
    hero_h1_line2: 'Track.',
    hero_h1_line3: 'Dominate.',
    hero_subtitle: 'The first fitness app that truly knows you. Track your progress, build habits and dominate every workout.',
    hero_cta1: 'Start for free',
    hero_cta2: 'See how it works',
    badge1_title: '+12%',
    badge1_sub: 'muscle mass / 90 days',
    badge2_title: 'New PR!',
    badge2_sub: 'bench press 140 kg',
    badge3_title: 'AI Scanner',
    badge3_sub: 'Body analyzed',
    phone_cta: 'Scan body',
    hps_weight_label: 'Current weight',
    hps_weight_start: 'Start: 65 kg',
    hps_weight_now: 'Now: 56.3 kg',
    fp_weight_label: 'Body weight',
    fp_weight_before: 'Before: 79 kg',
    fp_weight_after: 'Now: 68.4 kg',
    fp_timer_label: 'Current exercise',
    fp_timer_set1: 'Set 1 — 80 kg × 8',
    fp_timer_set2: 'Set 2 — 85 kg × 6',
    fp_timer_set3: 'Set 3 — 90 kg × 5',
    fp_timer_cta: 'Finish set',
    fp_macro_label: "Today's intake",
    fp_blood_label: 'Blood markers',
    fp_blood_chol: 'Cholesterol — high',
    fp_blood_vitd: 'Vitamin D — normal',
    fp_supp_label: "Today's stack",
    fp_supp_creatine: 'Creatine — 5 g',
    fp_supp_protein: 'Whey — 30 g',
    fp_supp_omega: 'Omega-3 — 2 g',
    fp_supp_vitd: 'Vit. D — 4000 IU',
    fp_cardio_label: 'Run — zone 3',
    fp_cardio_pace: 'Pace 5:12/km',
    fp_cardio_hr: 'HR 158 bpm',
    stats_sections: 'sections',
    stats_ranks: 'ranks',
    stats_motivation: 'motivation',
    stats_price: 'to start',
    features_title: 'Everything you need',
    features_subtitle: 'Complete fitness ecosystem in one app',
    features_p1_title: 'AI Scanner & Body',
    features_p1_desc: 'Snap a photo and AI instantly analyzes your body composition. Measurements, progress photos and a precise body composition tracker in one place — see the change the scale never shows.',
    features_p2_title: 'Training Plans & Hardcore Tracker',
    features_p2_desc: 'Hundreds of exercises, ready-made plans and AI-generated workouts built just for you. Timer, rest periods and PR tracking — no guessing, just numbers.',
    features_p3_title: 'Smart Nutrition & Biohacking Macros',
    features_p3_desc: 'Track calories, macros and hydration at a biohacker level. Eat smarter, not less — and optimize performance from the inside.',
    features_h1_title: 'Health & Blood Markers',
    features_h1_desc: '36 blood markers — thyroid, hormones, sugar, cholesterol, liver, vitamins. Snap a photo of your paper results and AI fills them in within 3 seconds.',
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Your personal trainer online 24/7. Knows your profile, blood values, workouts and nutrition. Gives brutally honest advice and adapts your plan for you.',
    features_h3_title: 'Community & Motivation Feed',
    features_h3_desc: 'Challenges, leaderboards and a feed full of community progress. XP, badges and 6 ranks push you closer to the BOOOM Monster title.',
    show_more_features_cta: 'Want to know what else BOOOM can do?',
    features_modal_title: 'Even more BOOOM features',
    features_modal_close: 'Close',
    ranks_title: 'Your path to the top',
    ranks_subtitle: '6 ranks. Every step pushes you further.',
    cta_title: 'Start your first workout today',
    cta_subtitle: 'Free. No credit card. No excuses.',
    cta_button: 'Launch BOOOM',
    footer_about: 'About',
    footer_contact: 'Contact',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. All rights reserved.',
    footer_founder: 'Laco, founder of BOOOM',
    footer_home: 'Home',
    // Navigation
    nav_enhanced_fitness: 'Beyond Natural',
    // LAB Teaser
    lab_badge: 'RESTRICTED ACCESS',
    lab_teaser_title: 'BOOOM LAB: Beyond Natural',
    lab_teaser_desc: 'Testosterone. Trenbolone. Anavar. Dianabol. Brutally honest deep-dive into the enhanced fitness world — mechanisms, side effects, blood markers and psychological reality.',
    lab_teaser_cta: 'Enter the forbidden zone',
    lab_teaser_disclaimer: '⚠️ For educational purposes only. BOOOM does not support or promote the use of anabolic steroids.',
    // LAB Page
    nav_back: 'Back to home',
    lab_hero_badge: 'EDUCATIONAL CONTENT',
    lab_hero_title: 'BOOOM LAB: Beyond Natural',
    lab_hero_desc: 'Brutally honest deep-dive into the enhanced fitness world. No romanticization, no moralizing — just facts, mechanisms, side effects and numbers you must track if you decided to take this path.',
    lab_disclaimer_title: '⚠️ IMPORTANT NOTICE:',
    lab_disclaimer_text: 'This content is intended purely for educational purposes. BOOOM does not support, promote or encourage the use of anabolic steroids. Any decisions regarding health and supplementation should be consulted with a qualified physician.',
    // Substances
    substances_tag: 'MAIN SUBSTANCES',
    substances_title: 'The Big Four: What You Need to Know',
    substances_subtitle: 'Mechanisms of action, dosing, side effects and detection',
    tst_title: 'Testosterone (TST)',
    tst_intro: 'Foundation of every cycle. Natural androgenic hormone your body produces. Enhanced users add it exogenously in doses 5-10× higher than natural production.',
    tst_mechanism: 'How it works',
    tst_m1: 'Increases protein synthesis in muscle cells',
    tst_m2: 'Suppresses catabolism (muscle breakdown)',
    tst_m3: 'Increases nitrogen retention and water retention',
    tst_m4: 'Stimulates erythropoiesis (red blood cell production)',
    tst_sides: 'Side effects',
    tst_s1: 'Aromatization: converts to estrogen → gynecomastia, water retention',
    tst_s2: 'Suppression of natural production: LH/FSH drops to zero',
    tst_s3: 'Cardiovascular: elevated hematocrit, increased blood pressure',
    tst_s4: 'Acne, hair loss (if genetically predisposed)',
    tst_doses: 'Typical doses',
    tst_doses_text: '250-500 mg/week (beginners), 500-750 mg/week (intermediate), 750+ mg/week (advanced risk zone)',
    tren_title: 'Trenbolone (TREN)',
    tren_intro: '"Strongest steroid on the planet." Originally designed for cattle. Extremely anabolic and androgenic. Delivers massive gains, but you pay a heavy price.',
    tren_mechanism: 'How it works',
    tren_m1: '5× more anabolic than testosterone',
    tren_m2: 'Does not convert to estrogen, but binds to progesterone receptors',
    tren_m3: 'Dramatically increases IGF-1 (insulin-like growth factor)',
    tren_m4: 'Inhibits cortisol (stress hormone)',
    tren_sides: 'Side effects',
    tren_s1: 'Night sweats, insomnia: brutally disrupted sleep',
    tren_s2: '"Tren cough": coughing fits after injection',
    tren_s3: 'Cardio dystopia: extremely impaired endurance',
    tren_s4: 'Aggression, anxiety, paranoia ("Tren rage")',
    tren_s5: 'Libido suppression post-cycle (can last months)',
    tren_doses: 'Typical doses',
    tren_doses_text: '200-400 mg/week (acetate form), 400-600 mg/week (enanthate). Beginners should stay far away.',
    var_title: 'Anavar (Oxandrolone)',
    var_intro: '"Female steroid." Mild but clean. Doesn\'t add huge mass, but gives dry, quality muscle. Popular in cutting phases.',
    var_mechanism: 'How it works',
    var_m1: 'Oral steroid, DHT derivative',
    var_m2: 'Low androgenic effect, minimal aromatization',
    var_m3: 'Increases strength without significant weight gain',
    var_m4: 'Supports fat burning and vascularity',
    var_sides: 'Side effects',
    var_s1: 'Hepatotoxicity: liver strain (AST/ALT ↑)',
    var_s2: 'Lipid profile: HDL drops, LDL rises',
    var_s3: 'Natural TST suppression (milder than injections)',
    var_s4: 'Relatively "safe" compared to other orals, but still not candy',
    var_doses: 'Typical doses',
    var_doses_text: '20-50 mg/day (women), 50-80 mg/day (men), expensive as hell — often counterfeited',
    dbol_title: 'Dianabol (Methandrostenolone)',
    dbol_intro: '"Dbol" — legend of the golden era of bodybuilding. Massive gains in short time, but much of it is water. Kickstarter for first 4-6 weeks of cycle.',
    dbol_mechanism: 'How it works',
    dbol_m1: 'Strong anabolic and androgenic activity',
    dbol_m2: 'Significant aromatization to estrogen',
    dbol_m3: 'Rapid gain in strength and mass (5-10 kg in 4 weeks)',
    dbol_m4: 'Increases glycogenolysis and protein synthesis',
    dbol_sides: 'Side effects',
    dbol_s1: 'Massive water retention: "moon face", edema',
    dbol_s2: 'Gynecomastia risk: high estrogenic activity',
    dbol_s3: 'Hepatotoxicity: liver suffers (17-alpha alkylated)',
    dbol_s4: 'Blood pressure: significant increase',
    dbol_s5: 'Acne, oily skin',
    dbol_doses: 'Typical doses',
    dbol_doses_text: '20-40 mg/day (beginners), 40-60 mg/day (advanced). Cheap but brutal on liver.',
    // Blood Markers
    markers_tag: 'HEALTH MARKERS',
    markers_title: '36 blood parameters you must track',
    markers_subtitle: 'Without monitoring = Russian roulette with your body',
    markers_intro: 'If you take PEDs and don\'t monitor blood values, you\'re playing with fire. Here are key markers BOOOM tracks and why they\'re critical.',
    marker_ast_alt: 'AST / ALT',
    marker_ast_alt_desc: 'Liver enzymes. If elevated, your liver is screaming for help. All oral steroids (Anavar, Dbol) shoot them sky high.',
    marker_hdl_ldl: 'HDL / LDL',
    marker_hdl_ldl_desc: 'Cholesterol. PEDs brutally suppress HDL (good) and raise LDL (bad). Heart attack and stroke risk rises exponentially.',
    marker_hematocrit: 'Hematocrit',
    marker_hematocrit_desc: '% of red blood cells in blood. Testosterone raises it. If it goes above 54%, blood becomes like syrup → clots, stroke.',
    marker_lh_fsh: 'LH / FSH',
    marker_lh_fsh_desc: 'Pituitary hormones controlling TST and sperm production. On cycle they drop to zero. If they don\'t return post-cycle = you\'re hypogonadal.',
    marker_e2: 'Estradiol (E2)',
    marker_e2_desc: 'Estrogen. If too high (from TST aromatization) → gyno, water retention. If too low (from AI overdose) → broken joints, dead libido.',
    marker_prolactin: 'Prolactin',
    marker_prolactin_desc: 'Trenbolone and Nandrolone raise it. High prolactin = erectile dysfunction, gynecomastia, "deca dick".',
    marker_creatinine: 'Creatinine / GFR',
    marker_creatinine_desc: 'Kidney function. Anabolics strain them. If GFR drops, kidneys are failing. Irreversible damage.',
    marker_tsh: 'TSH / T3 / T4',
    marker_tsh_desc: 'Thyroid. PEDs can disrupt it. If out of range, metabolism tanks, fatigue, depression, gains stop.',
    // Charts
    chart_tst_title: 'Chart 1: Natural vs Enhanced — Testosterone Levels',
    chart_tst_desc: 'Comparison of natural testosterone levels with enhanced version during active cycle',
    chart_tst_legend_natural: 'Natural production (male 20-40 years)',
    chart_tst_legend_enhanced: 'Enhanced cycle (500 mg TST/week)',
    chart_strength_title: 'Chart 2: Strength Rollercoaster — Cycle and crash',
    chart_strength_desc: 'What strength looks like during cycle and after if you don\'t do proper PCT (Post Cycle Therapy)',
    chart_strength_legend_on: 'Weeks 0-12: Exponential strength growth',
    chart_strength_legend_off: 'Weeks 12-20: Catastrophic drop without PCT',
    // Psychology
    psych_tag: 'PSYCHOLOGICAL REALITY',
    psych_title: 'God Mode vs Hormonal Hell',
    psych_subtitle: 'What nobody tells you: how PEDs affect your mind',
    psych_god_title: '🚀 "God Mode" (On Cycle)',
    psych_god_1: 'Unshakeable confidence',
    psych_god_2: 'Zero anxiety, aggression in gym is an advantage',
    psych_god_3: 'Libido through the roof (if estrogen is in range)',
    psych_god_4: 'Extreme motivation, "fuck" fatigue',
    psych_god_5: 'Feeling of invincibility, dominance in everything',
    psych_hell_title: '💀 "Hormonal Hell" (Post-Cycle)',
    psych_hell_1: 'Depression, anxiety, zero motivation',
    psych_hell_2: 'Dead libido, erectile dysfunction',
    psych_hell_3: 'Insomnia, irritability, emotional instability',
    psych_hell_4: 'Loss of all gains (muscle mass drops)',
    psych_hell_5: 'Feeling worthless — "who am I without roids?"',
    psych_outro: 'The truth is brutal: On cycle you feel like a god. Off cycle you feel like your dog died. Many get addicted precisely because of this psychological whiplash. Blast & cruise (endless cycle without breaks) becomes the norm because PCT is mentally unbearable.',
    // Detection
    detection_tag: 'GYM LORE',
    detection_title: 'How to spot someone who\'s not natural?',
    detection_subtitle: 'Visual cues that don\'t lie — no tests needed',
    detection_shoulders_title: '3D Delts (shoulders)',
    detection_shoulders_desc: 'Round, pumped shoulders with extreme separation. Androgen receptors in delts respond brutally to steroids.',
    detection_flushing_title: 'Flushing & Acne',
    detection_flushing_desc: 'Red face during training, acne on back and shoulders. Elevated heart rate + elevated hematocrit = permanent "pump".',
    detection_gut_title: '"Roid Gut" (Palumboism)',
    detection_gut_desc: 'Bloated stomach despite low body fat. Growth of internal organs from insulin + HGH. Modern bodybuilding epidemic.',
    detection_gains_title: 'Unrealistically fast gains',
    detection_gains_desc: 'If someone gains 15 kg of muscle in 12 weeks while leaning out — no, it\'s not chicken rice and broccoli.',
    detection_vascularity_title: 'Extreme vascularity',
    detection_vascularity_desc: 'Veins like hoses even at rest. Low fat + water retention in muscles + increased blood volume = roadmap look.',
    detection_strength_title: 'Superhuman strength at low bodyweight',
    detection_strength_desc: 'Bench 160 kg at 80 kg bodyweight and 8% body fat? Anavar + Tren stack. Natural limit is far lower.',
    // LAB CTA
    lab_cta_title: 'Track your health. No excuses.',
    // New index.html translations
    nav_features: 'Features',
    nav_thyroid: 'Thyroid',
    nav_diets_toggle: 'Diets & Intolerances ▾',
    nav_diets_mobile: 'Diets & Intolerances',
    nav_diet_lactose: '🥛 Lactose-Free Diet',
    nav_diet_gluten: '🌾 Gluten-Free Diet',
    nav_diet_histamine: '🧪 Histamine Intolerance',
    nav_diet_hashimoto: '🧬 Hashimoto\'s Thyroiditis',
    nav_ranks: 'Ranks',
    nav_story: 'Story',
    nav_mobile_cta: 'Download BOOOM for Free →',
    hero_stat1_label: 'App Sections',
    hero_stat2_label: 'Blood Parameters',
    hero_stat3_label: 'AI Coach',
    story_tag: 'Founder\'s Story',
    story_btn: 'Why did BOOOM start? My story.',
    feature_tag_ai_scan: 'AI scan',
    feature_tag_body_scan: 'Body scan',
    feature_tag_progress_pics: 'Progress pics',
    feature_tag_trends: 'Trends',
    feature_tag_exercises: 'Hundreds of exercises',
    feature_tag_ai_plans: 'AI plans',
    feature_tag_pr_tracking: 'PR tracking',
    feature_tag_timer: 'Timer',
    feature_tag_macros: 'Macros',
    feature_tag_calories: 'Calories',
    feature_tag_hydration: 'Hydration',
    feature_tag_biohacking: 'Biohacking',
    feature_tag_36_params: '36 parameters',
    feature_tag_time_trends: 'Time trends',
    feature_tag_alerts: 'Alerts',
    feature_tag_247: '24/7 online',
    feature_tag_personalized: 'Personalized',
    feature_tag_blood_values: 'Blood values',
    feature_tag_training_plans: 'Training plans',
    feature_tag_challenges: 'Challenges',
    feature_tag_leaderboards: 'Leaderboards',
    feature_tag_xp_ranks: 'XP & Ranks',
    feature_tag_feed: 'Feed',
    testimonials_tag: 'Community',
    testimonials_title: 'What our members say',
    testimonials_subtitle: 'Real stories. Real progress.',
    testimonials_rating: 'Rated by beta users',
    testimonial1_text: '"Finally an app that understands fitness isn\'t just about calories. Blood tracking opened my eyes — I found out I had low ferritin and that\'s why I stagnated for a year. BOOOM literally changed my life."',
    testimonial1_name: 'Marek Kováč',
    testimonial1_role: 'Powerlifter · Bratislava',
    testimonial2_text: '"I have Hashimoto and before BOOOM I had no idea what to eat and when to train. AI Coach explained connections that no trainer or doctor told me in such a human way. Now I finally have a system."',
    testimonial2_name: 'Zuzana Horáková',
    testimonial2_role: 'Mom & CrossFit Enthusiast · Žilina',
    testimonial3_text: '"I was 41 and thought stagnation was age. GPS tracking, blood values, AI plan — in 3 months I lost 9 kg while gaining muscle. This isn\'t an app, it\'s a personal trainer for the price of coffee."',
    testimonial3_name: 'Tomáš Novák',
    testimonial3_role: 'Cyclist & Father of Three · Košice',
    fomo_badge: 'Limited Early Access',
    fomo_title: 'BOOOM isn\'t an app for people<br>who come to the gym to take photos.',
    fomo_subtitle: 'We\'re building a community of grinders who want to see real numbers, not just likes. First 500 profiles get priority access to new features forever.',
    fomo_label: 'Currently available profiles:',
    fomo_meta_taken: '27 profiles taken',
    fomo_meta_free: '473 available',
    fomo_cta: 'Sign up for free →',
    diets_tag: 'Health & Diets',
    diets_title: 'More than just fitness',
    diets_subtitle: 'Comprehensive guides for people with specific health needs',
    teaser_thyroid_title: 'What you should know about thyroid',
    teaser_thyroid_desc: 'Hypothyroidism, hyperthyroidism, Hashimoto — symptoms, diet, supplementation and latest scientific studies. BOOOM founder\'s personal experience.',
    teaser_lactose_title: 'Lactose-Free Diet — Complete Guide',
    teaser_lactose_desc: 'What to eat, what to avoid and how not to lose important nutrients. Complete guide for people with lactose intolerance.',
    teaser_gluten_title: 'Gluten-Free Diet — For Celiacs',
    teaser_gluten_desc: 'What to eat, what to exclude, where gluten hides and how not to lose important nutrients. Complete guide.',
    teaser_histamine_title: 'Histamine Intolerance',
    teaser_histamine_desc: 'Headache after wine? Itchy skin after cheese? Maybe it\'s not an allergy. Complete guide to histamine intolerance.',
    teaser_hashimoto_title: 'Hashimoto\'s Thyroiditis — Diet & Supplementation',
    teaser_hashimoto_desc: 'Selenium, myo-inositol, gluten-free diet and everything science says about treating Hashimoto with diet. BOOOM founder\'s personal experience.',
    teaser_read_more: 'Read more →',
    cta_tag: 'Start today',
    cta_benefit1: 'Full access for free',
    cta_benefit2: 'AI Coach from day one',
    cta_benefit3: 'No commitment, cancel anytime',
    cta_note: 'Hundreds of people from SK, CZ and PL are already tracking their progress.',
    hero_scroll: 'Scroll',
    features_tag: 'Features',
    lab_cta_desc: 'Whether you\'re natural, enhanced, or just curious — BOOOM gives you comprehensive monitoring of 36 blood parameters, workouts, nutrition and your progress. See numbers. Understand body. Dominate.',
    lab_cta_button: 'Download BOOOM for free',
  },
  CS: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Vyzkoušej zdarma',
    hero_badge: '⚡ Fitness appka nové generace',
    hero_h1_line1: 'Cvič.',
    hero_h1_line2: 'Sleduj.',
    hero_h1_line3: 'Dominuj.',
    hero_subtitle: 'První fitness aplikace, která tě skutečně zná. Sleduj pokrok, buduj návyky a dominuj na každém tréninku.',
    hero_cta1: 'Začni zdarma',
    hero_cta2: 'Podívej jak to funguje',
    badge1_title: '+12%',
    badge1_sub: 'svalová hmota / 90 dní',
    badge2_title: 'Nové PR!',
    badge2_sub: 'benchpress 140 kg',
    badge3_title: 'AI skener',
    badge3_sub: 'Postava analyzována',
    phone_cta: 'Skenovat tělo',
    hps_weight_label: 'Aktuální váha',
    hps_weight_start: 'Start: 65 kg',
    hps_weight_now: 'Teď: 56.3 kg',
    fp_weight_label: 'Tělesná váha',
    fp_weight_before: 'Před: 79 kg',
    fp_weight_after: 'Teď: 68.4 kg',
    fp_timer_label: 'Aktuální cvik',
    fp_timer_set1: 'Série 1 — 80 kg × 8',
    fp_timer_set2: 'Série 2 — 85 kg × 6',
    fp_timer_set3: 'Série 3 — 90 kg × 5',
    fp_timer_cta: 'Dokončit sérii',
    fp_macro_label: 'Dnešní příjem',
    fp_blood_label: 'Krevní hodnoty',
    fp_blood_chol: 'Cholesterol — vysoký',
    fp_blood_vitd: 'Vitamín D — v normě',
    fp_supp_label: 'Dnešní suplementy',
    fp_supp_creatine: 'Kreatin — 5 g',
    fp_supp_protein: 'Whey — 30 g',
    fp_supp_omega: 'Omega-3 — 2 g',
    fp_supp_vitd: 'Vit. D — 4000 IU',
    fp_cardio_label: 'Běh — zóna 3',
    fp_cardio_pace: 'Tempo 5:12/km',
    fp_cardio_hr: 'Tep 158 bpm',
    stats_sections: 'sekcí',
    stats_ranks: 'ranků',
    stats_motivation: 'motivace',
    stats_price: 'start',
    features_title: 'Vše co potřebuješ',
    features_subtitle: 'Kompletní fitness ekosystém v jedné aplikaci',
    features_p1_title: 'AI Skener & Tělo',
    features_p1_desc: 'Vyfoť se a AI okamžitě zanalyzuje složení těla. Měření, fotky pokroku a přesný body composition tracker na jednom místě — vidíš změnu, kterou váha nikdy neukáže.',
    features_p2_title: 'Tréninkový plán & Hardcore Tracker',
    features_p2_desc: 'Stovky cviků, hotové plány a AI-generované tréninky přesně pro tebe. Časovač, pauzy a sledování PR — žádné odhady, jen čísla.',
    features_p3_title: 'Chytrá výživa & Biohacking Makra',
    features_p3_desc: 'Sleduj kalorie, makra a hydrataci na úrovni biohackera. Jez chytřeji, ne méně — a optimalizuj výkon zevnitř.',
    features_h1_title: 'Zdraví & Krevní parametry',
    features_h1_desc: '36 krevních parametrů — štítná žláza, hormony, cukr, cholesterol, játra, vitamíny. Vyfotíš výsledky z papíru a AI je vyplní za 3 sekundy.',
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Tvůj osobní trenér online 24/7. Zná tvůj profil, krevní hodnoty, tréninky i výživu. Radí brutálně upřímně a přizpůsobuje plán za tebe.',
    features_h3_title: 'Komunita & Motivation Feed',
    features_h3_desc: 'Výzvy, žebříčky a feed plný progresu komunity. XP, odznaky a 6 ranků tě posouvají blíž k titulu BOOOM Monster.',
    show_more_features_cta: 'Chceš vědět, co BOOOM umí ještě víc?',
    features_modal_title: 'Ještě víc BOOOM funkcí',
    features_modal_close: 'Zavřít',
    ranks_title: 'Tvoje cesta na vrchol',
    ranks_subtitle: '6 ranků. Každý krok tě posouvá dál.',
    cta_title: 'Začni svůj první trénink dnes',
    cta_subtitle: 'Zdarma. Bez kreditky. Bez výmluv.',
    cta_button: 'Spustit BOOOM',
    footer_about: 'O nás',
    footer_contact: 'Kontakt',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Všechna práva vyhrazena.',
    footer_founder: 'Laco, zakladatel BOOOM',
    footer_home: 'Domů',
    // Navigation
    nav_enhanced_fitness: 'Za hranicí naturalu',
    // LAB (Czech uses same content as SK with minor spelling differences)
    lab_badge: 'RESTRICTED ACCESS',
    lab_teaser_title: 'BOOOM LAB: Za hranicí naturalu',
    lab_teaser_desc: 'Testosteron. Trenbolon. Anavar. Dianabol. Brutálně upřímný deep-dive do světa enhanced fitness — mechanismy, vedlejší účinky, krevní markery a psychologická realita.',
    lab_teaser_cta: 'Vstoupit do zakázané zóny',
    lab_teaser_disclaimer: '⚠️ Pouze pro vzdělávací účely. BOOOM nepodporuje ani nepropaguje používání anabolických steroidů.',
    nav_back: 'Zpět na hlavní',
    lab_hero_badge: 'VZDĚLÁVACÍ OBSAH',
    lab_hero_title: 'BOOOM LAB: Za hranicí naturalu',
    lab_cta_title: 'Sleduj své zdraví. Žádné výmluvy.',
    lab_cta_desc: 'Ať už jsi natural, enhanced, nebo jen zvědavý — BOOOM ti dává komplexní monitoring 36 krevních parametrů, tréninků, výživy a tvého pokroku.',
    lab_cta_button: 'Stáhnout BOOOM zdarma',
    // Complete LAB page translations (Czech)
    lab_hero_desc: 'Brutálně upřímný deep-dive do světa enhanced fitness. Bez romantizace, bez moralizování — jen fakta, mechanismy, vedlejší účinky a čísla, která musíš sledovat, pokud ses rozhodl jít touto cestou.',
    lab_disclaimer_title: '⚠️ DŮLEŽITÉ UPOZORNĚNÍ:',
    lab_disclaimer_text: 'Tento obsah je určen čistě pro vzdělávací účely. BOOOM nepodporuje, nepropaguje ani nevyzývá k používání anabolických steroidů. Jakákoliv rozhodnutí týkající se zdraví a suplementace by měla být konzultována s kvalifikovaným lékařem.',
    substances_tag: 'HLAVNÍ LÁTKY',
    substances_title: 'Velká čtyřka: Co potřebuješ vědět',
    substances_subtitle: 'Mechanismy účinku, dávkování, vedlejší efekty a detekce',
    markers_tag: 'ZDRAVOTNÍ MARKERY',
    markers_title: '36 krevních parametrů, které musíš sledovat',
    markers_subtitle: 'Bez monitorování = ruská ruleta s tvým tělem',
    markers_intro: 'Pokud bereš PEDs a nemonitoruješ krevní hodnoty, hraješ si s ohněm. Zde jsou klíčové markery, které BOOOM trackuje, a proč jsou kritické.',
    psych_tag: 'PSYCHOLOGICKÁ REALITA',
    psych_title: 'God Mode vs Hormonal Hell',
    psych_subtitle: 'Co nikdo neřekne: jak PEDs ovlivňují tvou hlavu',
    detection_tag: 'GYM LORE',
    detection_title: 'Jak poznáš, že někdo není natural?',
    detection_subtitle: 'Visual cues, které nepustí — žádné testy nepotřebné',
    chart_tst_title: 'Graf 1: Natural vs Enhanced — Hladiny testosteronu',
    chart_tst_desc: 'Porovnání přirozených hladin testosteronu s enhanced verzí během aktivního cyklu',
    chart_tst_legend_natural: 'Přirozená produkce (muž 20-40 let)',
    chart_tst_legend_enhanced: 'Enhanced cycle (500 mg TST/týden)',
    chart_strength_title: 'Graf 2: Strength Rollercoaster — Cyklus a crash',
    chart_strength_desc: 'Jak vypadá síla během cyklu a po něm, pokud neděláš správně PCT (Post Cycle Therapy)',
    chart_strength_legend_on: 'Týdny 0-12: Exponenciální růst síly',
    chart_strength_legend_off: 'Týdny 12-20: Katastrofický pokles bez PCT',
    // Substances (Czech)
    tst_title: 'Testosteron (TST)',
    tst_intro: 'Základ každého cyklu. Přirozený androgénní hormon, který tvoje tělo vyrábí. Enhanced uživatelé ho přidávají exogenně v dávkách 5-10× vyšších než přirozená produkce.',
    tst_mechanism: 'Jak funguje',
    tst_m1: 'Zvyšuje syntézu bílkovin ve svalových buňkách',
    tst_m2: 'Potlačuje katabolismus (rozklad svalů)',
    tst_m3: 'Zvyšuje retenci dusíku a zadržování vody',
    tst_m4: 'Stimuluje erytropoézu (tvorbu červených krvinek)',
    tst_sides: 'Vedlejší účinky',
    tst_s1: 'Aromatizace: konverze na estrogén → gynekomastie, zadržování vody',
    tst_s2: 'Potlačení přirozené produkce: LH/FSH klesá na nulu',
    tst_s3: 'Kardiovaskulární: zvýšený hematokrit, nárůst krevního tlaku',
    tst_s4: 'Akné, plešatost (pokud jsi geneticky predisponován)',
    tst_doses: 'Typické dávky',
    tst_doses_text: '250-500 mg/týden (beginners), 500-750 mg/týden (intermediate), 750+ mg/týden (advanced risk zone)',
    tren_title: 'Trenbolon (TREN)',
    tren_intro: '"Nejsilnější steroid na planetě." Původně určený pro dobytek. Extrémně anabolický i androgénní. Dává obrovské gainy, ale platíš za to tvrdou cenou.',
    tren_mechanism: 'Jak funguje',
    tren_m1: '5× anaboličtější než testosteron',
    tren_m2: 'Nekonvertuje na estrogén, ale váže se na progesteronové receptory',
    tren_m3: 'Dramaticky zvyšuje IGF-1 (inzulínu podobný růstový faktor)',
    tren_m4: 'Inhibuje kortizol (stresový hormon)',
    tren_sides: 'Vedlejší účinky',
    tren_s1: 'Noční pocení, insomnie: brutálně narušený spánek',
    tren_s2: '"Tren cough": záchvaty kašle po injekci',
    tren_s3: 'Kardio dystopie: extrémně zhoršená vytrvalost',
    tren_s4: 'Agresivita, úzkost, paranoia ("Tren rage")',
    tren_s5: 'Potlačení libida post-cycle (může trvat měsíce)',
    tren_doses: 'Typické dávky',
    tren_doses_text: '200-400 mg/týden (acetát form), 400-600 mg/týden (enanthate). Beginners by se měli držet daleko.',
    var_title: 'Anavar (Oxandrolone)',
    var_intro: '"Ženský steroid." Mírný, ale čistý. Nepřidává velké gainy, ale dává suchou, kvalitní svalovinu. Oblíbený v cutting fázích.',
    var_mechanism: 'Jak funguje',
    var_m1: 'Orální steroid, DHT derivát',
    var_m2: 'Nízký androgénní efekt, minimální aromatizace',
    var_m3: 'Zvyšuje sílu bez výrazného nárůstu hmotnosti',
    var_m4: 'Podporuje spalování tuků a vaskularitu',
    var_sides: 'Vedlejší účinky',
    var_s1: 'Hepatotoxicita: zatížení jater (AST/ALT ↑)',
    var_s2: 'Lipidový profil: pokles HDL, nárůst LDL',
    var_s3: 'Potlačení přirozeného TST (mírnější než injekce)',
    var_s4: 'Relativně "bezpečný" v porovnání s jinými orálky, ale stále ne candy',
    var_doses: 'Typické dávky',
    var_doses_text: '20-50 mg/den (ženy), 50-80 mg/den (muži), drahý jako čert — často falšovaný',
    dbol_title: 'Dianabol (Methandrostenolone)',
    dbol_intro: '"Dbol" — legenda zlaté éry bodybuildingu. Masivní gainy za krátký čas, ale velká část je voda. Kickstarter prvních 4-6 týdnů cyklu.',
    dbol_mechanism: 'Jak funguje',
    dbol_m1: 'Silná anabolická i androgénní aktivita',
    dbol_m2: 'Výrazná aromatizace na estrogén',
    dbol_m3: 'Rychlý nárůst síly a hmotnosti (5-10 kg za 4 týdny)',
    dbol_m4: 'Zvyšuje glykogenolýzu a syntézu bílkovin',
    dbol_sides: 'Vedlejší účinky',
    dbol_s1: 'Masivní zadržování vody: "moon face", edémy',
    dbol_s2: 'Gynekomastie risk: vysoká estrogenová aktivita',
    dbol_s3: 'Hepatotoxicita: játra trpí (17-alpha alkylovaný)',
    dbol_s4: 'Krevní tlak: značný nárůst',
    dbol_s5: 'Akné, mastná kůže',
    dbol_doses: 'Typické dávky',
    dbol_doses_text: '20-40 mg/den (beginners), 40-60 mg/den (advanced). Levný, ale brutální na játra.',
    marker_ast_alt: 'AST / ALT',
    marker_ast_alt_desc: 'Jaterní enzymy. Pokud jsou zvýšené, tvoje játra křičí o pomoc. Všechny orální steroidy (Anavar, Dbol) je vystřelují nahoru.',
    marker_hdl_ldl: 'HDL / LDL',
    marker_hdl_ldl_desc: 'Cholesterol. PEDs brutálně potlačují HDL (dobrý) a zvyšují LDL (špatný). Riziko infarktu a mrtvice exponenciálně roste.',
    marker_hematocrit: 'Hematokrit',
    marker_hematocrit_desc: '% červených krvinek v krvi. Testosteron ho zvyšuje. Pokud jde nad 54 %, krev je jako sirup → tromby, mozková příhoda.',
    marker_lh_fsh: 'LH / FSH',
    marker_lh_fsh_desc: 'Hormony hypofýzy řídící produkci TST a spermií. Na cycle padají na nulu. Pokud se nevrátí post-cycle = jsi hypogonadální.',
    marker_e2: 'Estradiol (E2)',
    marker_e2_desc: 'Estrogén. Pokud je příliš vysoký (z aromatizace TST) → gyno, zadržování vody. Pokud příliš nízký (z AI overdose) → zlomené klouby, libido v prdeli.',
    marker_prolactin: 'Prolaktin',
    marker_prolactin_desc: 'Trenbolon a Nandrolon ho zvyšují. Vysoký prolaktin = erectile dysfunction, gynekomastie, "deca dick".',
    marker_creatinine: 'Kreatinin / GFR',
    marker_creatinine_desc: 'Funkce ledvin. Anabolika je zatěžují. Pokud klesá GFR, ledviny selhávají. Ireverzibilní poškození.',
    marker_tsh: 'TSH / T3 / T4',
    marker_tsh_desc: 'Štítná žláza. PEDs ji mohou narušit. Pokud jsou mimo, metabolismus jde do prdele, únava, deprese, přírostky končí.',
    psych_god_title: '🚀 "God Mode" (On Cycle)',
    psych_god_1: 'Neotřesitelná sebedůvěra',
    psych_god_2: 'Zero úzkosti, agresivita v gymu je výhodou',
    psych_god_3: 'Libido přes střechu (pokud je estrogén v normě)',
    psych_god_4: 'Extrémní motivace, "na hovno" únava',
    psych_god_5: 'Pocit nesmrtelnosti, dominance ve všem',
    psych_hell_title: '💀 "Hormonal Hell" (Post-Cycle)',
    psych_hell_1: 'Deprese, úzkosti, nulová motivace',
    psych_hell_2: 'Libido v prdeli, erectile dysfunction',
    psych_hell_3: 'Insomnie, podrážděnost, emocionální labilita',
    psych_hell_4: 'Ztráta všech gainsů (svalová hmota padá)',
    psych_hell_5: 'Pocit, že jsi zbytečný — "kdo jsem bez roidů?"',
    psych_outro: 'Pravda je brutální: Na cycle se cítíš jako bůh. Off cycle máš pocit, že ti zemřel pes. Mnoho lidí se dostává do závislosti právě kvůli tomuto psychologickému whiplashu. Blast & cruise (nekonečný cycle bez pauzy) se stává normou, protože PCT je psychicky neúnosné.',
    detection_shoulders_title: '3D Delts (ramena)',
    detection_shoulders_desc: 'Kulaté, nafouklé ramena s extrémní separací. Androgénní receptory v deltatech reagují brutálně na steroidy.',
    detection_flushing_title: 'Flushing & Akné',
    detection_flushing_desc: 'Červená tvář během tréninku, akné na zádech a ramenou. Zvýšený tep + zvýšený hematokrit = permanentní "pump".',
    detection_gut_title: '"Roid Gut" (Palumboism)',
    detection_gut_desc: 'Nafouklé břicho navzdory nízkému tuku. Růst vnitřních orgánů z inzulínu + HGH. Moderní bodybuilding epidemie.',
    detection_gains_title: 'Nereálně rychlé gainy',
    detection_gains_desc: 'Pokud někdo za 12 týdnů nabere 15 kg svalové hmoty a zároveň zhubne — ne, nejde o kuřecí rýži a brokolici.',
    detection_vascularity_title: 'Extrémní vaskularita',
    detection_vascularity_desc: 'Žíly jako hadice i v klidu. Nízký tuk + zadržování vody ve svalech + zvýšený objem krve = roadmap look.',
    detection_strength_title: 'Nadlidská síla při nízké váze',
    detection_strength_desc: 'Bench 160 kg při 80 kg tělesné váze a 8 % tuku? Anavar + Tren stack. Natural limit je daleko níže.',
    // New index.html translations
    nav_features: 'Funkce',
    nav_thyroid: 'Štítná žláza',
    nav_diets_toggle: 'Diety & intolerance ▾',
    nav_diets_mobile: 'Diety & intolerance',
    nav_diet_lactose: '🥛 Bezlaktózová dieta',
    nav_diet_gluten: '🌾 Bezlepková dieta',
    nav_diet_histamine: '🧪 Histaminová intolerance',
    nav_diet_hashimoto: '🧬 Hashimotova tyreoiditida',
    nav_ranks: 'Ranky',
    nav_story: 'Příběh',
    nav_mobile_cta: 'Stáhnout BOOOM zdarma →',
    hero_stat1_label: 'Sekcí appky',
    hero_stat2_label: 'Krevních parametrů',
    hero_stat3_label: 'AI Coach',
    story_tag: 'Příběh zakladatele',
    story_btn: 'Proč vznikl BOOOM? Můj příběh.',
    feature_tag_ai_scan: 'AI sken',
    feature_tag_body_scan: 'Body scan',
    feature_tag_progress_pics: 'Fotky pokroku',
    feature_tag_trends: 'Trendy',
    feature_tag_exercises: 'Stovky cviků',
    feature_tag_ai_plans: 'AI plány',
    feature_tag_pr_tracking: 'PR tracking',
    feature_tag_timer: 'Časovač',
    feature_tag_macros: 'Makra',
    feature_tag_calories: 'Kalorie',
    feature_tag_hydration: 'Hydratace',
    feature_tag_biohacking: 'Biohacking',
    feature_tag_36_params: '36 parametrů',
    feature_tag_time_trends: 'Trendy v čase',
    feature_tag_alerts: 'Alarmy',
    feature_tag_247: '24/7 online',
    feature_tag_personalized: 'Personalizovaný',
    feature_tag_blood_values: 'Krevní hodnoty',
    feature_tag_training_plans: 'Plány tréninků',
    feature_tag_challenges: 'Výzvy',
    feature_tag_leaderboards: 'Žebříčky',
    feature_tag_xp_ranks: 'XP & Ranky',
    feature_tag_feed: 'Feed',
    testimonials_tag: 'Komunita',
    testimonials_title: 'Co říkají naši dříči',
    testimonials_subtitle: 'Skutečné příběhy. Skutečný pokrok.',
    testimonials_rating: 'Hodnoceno beta uživateli',
    testimonial1_text: '"Konečně appka, která chápe, že fitness není jen o kaloriích. Sledování krevních hodnot mi otevřelo oči — zjistil jsem, že mám nízký feritin a to byl důvod, proč jsem stagnoval rok. BOOOM mi doslova změnil život."',
    testimonial1_name: 'Marek Kováč',
    testimonial1_role: 'Powerlifter · Bratislava',
    testimonial2_text: '"Mám Hashimoto a před BOOOM jsem vůbec nevěděla, co smím jíst a kdy cvičit. AI Coach mi vysvětlil souvislosti, které mi žádný trenér ani lekař neřekl tak lidsky. Teď mám konečně systém."',
    testimonial2_name: 'Zuzana Horáková',
    testimonial2_role: 'Maminka & CrossFit nadšenkyně · Žilina',
    testimonial3_text: '"Bylo mi 41 let a myslel jsem, že stagnace je věk. GPS tracking, krevní hodnoty, AI plán — za 3 měsíce jsem zhubl 9 kg a přitom nabral svalovku. Tohle není appka, tohle je osobní trenér za cenu kávy."',
    testimonial3_name: 'Tomáš Novák',
    testimonial3_role: 'Cyklista & Otec tří dětí · Košice',
    fomo_badge: 'Omezený Early Access',
    fomo_title: 'BOOOM není appka pro lidi,<br>co chodí do fitka fotit se.',
    fomo_subtitle: 'Stavíme komunitu dřičů, kteří chtějí vidět reálná čísla, ne jen lajky. Prvních 500 profilů má přednostní přístup k novým funkcím navždy.',
    fomo_label: 'Aktuálně volných profilů:',
    fomo_meta_taken: '27 profilů obsazených',
    fomo_meta_free: '473 volných',
    fomo_cta: 'Zaregistrovat se zdarma →',
    diets_tag: 'Zdraví & Diety',
    diets_title: 'Více než jen fitness',
    diets_subtitle: 'Komplexní průvodci pro lidi se specifickými zdravotními potřebami',
    teaser_thyroid_title: 'Co bys měl vědět o štítné žláze',
    teaser_thyroid_desc: 'Hypotyreóza, hypertyreóza, Hashimoto — příznaky, dieta, suplementace a nejnovější vědecké studie. Osobní zkušenost zakladatele BOOOM.',
    teaser_lactose_title: 'Bezlaktózová dieta — kompletní průvodce',
    teaser_lactose_desc: 'Co jíst, co vynechat a jak nepřijít o důležité živiny. Kompletní průvodce pro lidi s laktózovou intolerancí.',
    teaser_gluten_title: 'Bezlepková dieta — pro celiaky',
    teaser_gluten_desc: 'Co jíst, co vyloučit, kde se skrývá lepek a jak nepřijít o důležité živiny. Kompletní průvodce.',
    teaser_histamine_title: 'Histaminová intolerance',
    teaser_histamine_desc: 'Bolí tě hlava po víně? Svrbí tě kůže po sýru? Možná to není alergie. Kompletní průvodce histaminovou intolerancí.',
    teaser_hashimoto_title: 'Hashimotova tyreoiditida — dieta a suplementace',
    teaser_hashimoto_desc: 'Selen, myo-inositol, bezlepková dieta a všechno co věda říká o léčbě Hashimota stravou. Osobní zkušenost zakladatele BOOOM.',
    teaser_read_more: 'Číst více →',
    cta_tag: 'Začni dnes',
    cta_benefit1: 'Kompletní přístup zdarma',
    cta_benefit2: 'AI Coach od prvního dne',
    cta_benefit3: 'Bez závazků, zruš kdykoliv',
    cta_note: 'Stovky lidí z SK, CZ a PL už sledují svůj pokrok.',
    hero_scroll: 'Scroll',
    features_tag: 'Funkce',
  },
  PL: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Wypróbuj za darmo',
    hero_badge: '⚡ Aplikacja fitness nowej generacji',
    hero_h1_line1: 'Trenuj.',
    hero_h1_line2: 'Śledź.',
    hero_h1_line3: 'Dominuj.',
    hero_subtitle: 'Pierwsza aplikacja fitness, która naprawdę cię zna. Śledź postępy, buduj nawyki i dominuj na każdym treningu.',
    hero_cta1: 'Zacznij za darmo',
    hero_cta2: 'Zobacz jak to działa',
    badge1_title: '+12%',
    badge1_sub: 'masa mięśniowa / 90 dni',
    badge2_title: 'Nowy PR!',
    badge2_sub: 'wyciskanie 140 kg',
    badge3_title: 'Skaner AI',
    badge3_sub: 'Ciało przeanalizowane',
    phone_cta: 'Skanuj ciało',
    hps_weight_label: 'Aktualna waga',
    hps_weight_start: 'Start: 65 kg',
    hps_weight_now: 'Teraz: 56.3 kg',
    fp_weight_label: 'Masa ciała',
    fp_weight_before: 'Przed: 79 kg',
    fp_weight_after: 'Teraz: 68.4 kg',
    fp_timer_label: 'Aktualne ćwiczenie',
    fp_timer_set1: 'Seria 1 — 80 kg × 8',
    fp_timer_set2: 'Seria 2 — 85 kg × 6',
    fp_timer_set3: 'Seria 3 — 90 kg × 5',
    fp_timer_cta: 'Zakończ serię',
    fp_macro_label: 'Dzisiejsze spożycie',
    fp_blood_label: 'Wyniki krwi',
    fp_blood_chol: 'Cholesterol — wysoki',
    fp_blood_vitd: 'Witamina D — w normie',
    fp_supp_label: 'Dzisiejsze suplementy',
    fp_supp_creatine: 'Kreatyna — 5 g',
    fp_supp_protein: 'Białko — 30 g',
    fp_supp_omega: 'Omega-3 — 2 g',
    fp_supp_vitd: 'Wit. D — 4000 IU',
    fp_cardio_label: 'Bieg — strefa 3',
    fp_cardio_pace: 'Tempo 5:12/km',
    fp_cardio_hr: 'Puls 158 bpm',
    stats_sections: 'sekcji',
    stats_ranks: 'rang',
    stats_motivation: 'motywacji',
    stats_price: 'start',
    features_title: 'Wszystko czego potrzebujesz',
    features_subtitle: 'Kompletny ekosystem fitness w jednej aplikacji',
    features_p1_title: 'AI Skaner & Ciało',
    features_p1_desc: 'Zrób zdjęcie i AI natychmiast przeanalizuje skład twojego ciała. Pomiary, zdjęcia postępu i precyzyjny body composition tracker w jednym miejscu — zobacz zmianę, której waga nigdy nie pokaże.',
    features_p2_title: 'Plan treningowy & Hardcore Tracker',
    features_p2_desc: 'Setki ćwiczeń, gotowe plany i treningi generowane przez AI stworzone właśnie dla ciebie. Timer, przerwy i śledzenie PR — żadnych domysłów, tylko liczby.',
    features_p3_title: 'Inteligentne żywienie & Biohacking Macros',
    features_p3_desc: 'Śledź kalorie, makro i nawodnienie na poziomie biohackera. Jedz mądrzej, nie mniej — i optymalizuj wydajność od wewnątrz.',
    features_h1_title: 'Zdrowie & Parametry krwi',
    features_h1_desc: '36 parametrów krwi — tarczyca, hormony, cukier, cholesterol, wątroba, witaminy. Zrób zdjęcie wyników z papieru, a AI uzupełni je w 3 sekundy.',
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Twój osobisty trener online 24/7. Zna twój profil, wyniki krwi, treningi i dietę. Radzi brutalnie szczerze i dopasowuje plan za ciebie.',
    features_h3_title: 'Społeczność & Motivation Feed',
    features_h3_desc: 'Wyzwania, rankingi i feed pełen postępów społeczności. XP, odznaki i 6 rang przybliżają cię do tytułu BOOOM Monster.',
    show_more_features_cta: 'Chcesz wiedzieć, co jeszcze umie BOOOM?',
    features_modal_title: 'Jeszcze więcej funkcji BOOOM',
    features_modal_close: 'Zamknij',
    ranks_title: 'Twoja droga na szczyt',
    ranks_subtitle: '6 rang. Każdy krok pcha cię dalej.',
    cta_title: 'Zacznij swój pierwszy trening dziś',
    cta_subtitle: 'Za darmo. Bez karty kredytowej. Bez wymówek.',
    cta_button: 'Uruchom BOOOM',
    footer_about: 'O nas',
    footer_contact: 'Kontakt',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Wszelkie prawa zastrzeżone.',
    footer_founder: 'Laco, założyciel BOOOM',
    footer_home: 'Strona główna',
    // Navigation
    nav_enhanced_fitness: 'Poza granicą naturalu',
    // LAB (Polish)
    lab_badge: 'RESTRICTED ACCESS',
    lab_teaser_title: 'BOOOM LAB: Poza naturalnym',
    lab_teaser_desc: 'Testosteron. Trenbolon. Anavar. Dianabol. Brutalnie szczery deep-dive w świat enhanced fitness — mechanizmy, skutki uboczne, markery krwi i psychologiczna rzeczywistość.',
    lab_teaser_cta: 'Wejdź do zakazanej strefy',
    lab_teaser_disclaimer: '⚠️ Tylko w celach edukacyjnych. BOOOM nie popiera ani nie promuje używania sterydów anabolicznych.',
    nav_back: 'Powrót do strony głównej',
    lab_hero_badge: 'TREŚĆ EDUKACYJNA',
    lab_hero_title: 'BOOOM LAB: Poza naturalnym',
    lab_cta_title: 'Śledź swoje zdrowie. Bez wymówek.',
    lab_cta_desc: 'Niezależnie od tego, czy jesteś natural, enhanced, czy po prostu ciekawy — BOOOM daje ci kompleksowy monitoring 36 parametrów krwi, treningów, odżywiania i twojego postępu.',
    lab_cta_button: 'Pobierz BOOOM za darmo',
    // Complete LAB page translations (Polish)
    lab_hero_desc: 'Brutalnie szczery deep-dive w świat enhanced fitness. Bez romantyzacji, bez moralizowania — tylko fakty, mechanizmy, skutki uboczne i liczby, które musisz śledzić, jeśli zdecydowałeś się iść tą drogą.',
    lab_disclaimer_title: '⚠️ WAŻNE POWIADOMIENIE:',
    lab_disclaimer_text: 'Ta treść jest przeznaczona wyłącznie do celów edukacyjnych. BOOOM nie wspiera, nie promuje ani nie zachęca do używania sterydów anabolicznych. Wszelkie decyzje dotyczące zdrowia i suplementacji powinny być skonsultowane z wykwalifikowanym lekarzem.',
    substances_tag: 'GŁÓWNE SUBSTANCJE',
    substances_title: 'Wielka czwórka: Co musisz wiedzieć',
    substances_subtitle: 'Mechanizmy działania, dawkowanie, skutki uboczne i wykrywanie',
    markers_tag: 'MARKERY ZDROWOTNE',
    markers_title: '36 parametrów krwi, które musisz śledzić',
    markers_subtitle: 'Bez monitorowania = rosyjska ruletka z twoim ciałem',
    markers_intro: 'Jeśli bierzesz PEDs i nie monitorujesz wartości krwi, bawisz się z ogniem. Oto kluczowe markery, które BOOOM śledzi i dlaczego są krytyczne.',
    psych_tag: 'RZECZYWISTOŚĆ PSYCHOLOGICZNA',
    psych_title: 'God Mode vs Hormonal Hell',
    psych_subtitle: 'Czego nikt ci nie powie: jak PEDs wpływają na twój umysł',
    detection_tag: 'GYM LORE',
    detection_title: 'Jak rozpoznać, że ktoś nie jest natural?',
    detection_subtitle: 'Wizualne wskazówki, które nie kłamią — żadne testy niepotrzebne',
    chart_tst_title: 'Wykres 1: Natural vs Enhanced — Poziomy testosteronu',
    chart_tst_desc: 'Porównanie naturalnych poziomów testosteronu z enhanced wersją podczas aktywnego cyklu',
    chart_tst_legend_natural: 'Naturalna produkcja (mężczyzna 20-40 lat)',
    chart_tst_legend_enhanced: 'Enhanced cycle (500 mg TST/tydzień)',
    chart_strength_title: 'Wykres 2: Strength Rollercoaster — Cykl i crash',
    chart_strength_desc: 'Jak wygląda siła podczas cyklu i po nim, jeśli nie robisz właściwego PCT (Post Cycle Therapy)',
    chart_strength_legend_on: 'Tygodnie 0-12: Wykładniczy wzrost siły',
    chart_strength_legend_off: 'Tygodnie 12-20: Katastrofalny spadek bez PCT',
    // Substances (Polish)
    tst_title: 'Testosteron (TST)',
    tst_intro: 'Podstawa każdego cyklu. Naturalny hormon androgenny, który produkuje twoje ciało. Enhanced użytkownicy dodają go egzogennie w dawkach 5-10× wyższych niż naturalna produkcja.',
    tst_mechanism: 'Jak działa',
    tst_m1: 'Zwiększa syntezę białek w komórkach mięśniowych',
    tst_m2: 'Tłumi katabolizm (rozpad mięśni)',
    tst_m3: 'Zwiększa retencję azotu i zatrzymywanie wody',
    tst_m4: 'Stymuluje erytropoezę (tworzenie czerwonych krwinek)',
    tst_sides: 'Skutki uboczne',
    tst_s1: 'Aromatyzacja: konwersja do estrogenu → ginekomastia, zatrzymywanie wody',
    tst_s2: 'Tłumienie naturalnej produkcji: LH/FSH spada do zera',
    tst_s3: 'Kardiowasku​larne: podwyższony hematokryt, wzrost ciśnienia krwi',
    tst_s4: 'Trądzik, łysienie (jeśli jesteś genetycznie predysponowany)',
    tst_doses: 'Typowe dawki',
    tst_doses_text: '250-500 mg/tydzień (beginners), 500-750 mg/tydzień (intermediate), 750+ mg/tydzień (advanced risk zone)',
    tren_title: 'Trenbolon (TREN)',
    tren_intro: '"Najsilniejszy steroid na planecie." Pierwotnie przeznaczony dla bydła. Ekstremalnie anaboliczny i androgenny. Daje ogromne przyrosty, ale płacisz za to wysoką cenę.',
    tren_mechanism: 'Jak działa',
    tren_m1: '5× bardziej anaboliczny niż testosteron',
    tren_m2: 'Nie konwertuje do estrogenu, ale wiąże się z receptorami progesteronowymi',
    tren_m3: 'Dramatycznie zwiększa IGF-1 (insulinopodobny czynnik wzrostu)',
    tren_m4: 'Inhibuje kortyzol (hormon stresu)',
    tren_sides: 'Skutki uboczne',
    tren_s1: 'Nocne poty, bezsenność: brutalnie zakłócony sen',
    tren_s2: '"Tren cough": napady kaszlu po iniekcji',
    tren_s3: 'Kardio dystopia: ekstremalnie pogorszona wytrzymałość',
    tren_s4: 'Agresja, lęk, paranoia ("Tren rage")',
    tren_s5: 'Tłumienie libido post-cycle (może trwać miesiące)',
    tren_doses: 'Typowe dawki',
    tren_doses_text: '200-400 mg/tydzień (forma octanowa), 400-600 mg/tydzień (enanthate). Beginners powinni trzymać się z daleka.',
    var_title: 'Anavar (Oxandrolon)',
    var_intro: '"Steroid kobiecy." Łagodny, ale czysty. Nie dodaje wielkich przyrostów, ale daje suchą, jakościową muskulaturę. Popularny w fazach cuttingu.',
    var_mechanism: 'Jak działa',
    var_m1: 'Steroid doustny, pochodna DHT',
    var_m2: 'Niski efekt androgenny, minimalna aromatyzacja',
    var_m3: 'Zwiększa siłę bez znacznego przyrostu masy',
    var_m4: 'Wspiera spalanie tłuszczu i waskularyzację',
    var_sides: 'Skutki uboczne',
    var_s1: 'Hepatotoksyczność: obciążenie wątroby (AST/ALT ↑)',
    var_s2: 'Profil lipidowy: spadek HDL, wzrost LDL',
    var_s3: 'Tłumienie naturalnego TST (łagodniejsze niż iniekcje)',
    var_s4: 'Względnie "bezpieczny" w porównaniu z innymi doustnymi, ale wciąż nie cukierek',
    var_doses: 'Typowe dawki',
    var_doses_text: '20-50 mg/dzień (kobiety), 50-80 mg/dzień (mężczyźni), drogi jak diabli — często podrabiany',
    dbol_title: 'Dianabol (Methandrostenolon)',
    dbol_intro: '"Dbol" — legenda złotej ery bodybuildingu. Masywne przyrosty w krótkim czasie, ale duża część to woda. Kickstarter pierwszych 4-6 tygodni cyklu.',
    dbol_mechanism: 'Jak działa',
    dbol_m1: 'Silna aktywność anaboliczna i androgenna',
    dbol_m2: 'Wyraźna aromatyzacja do estrogenu',
    dbol_m3: 'Szybki przyrost siły i masy (5-10 kg w 4 tygodnie)',
    dbol_m4: 'Zwiększa glikogenolizę i syntezę białek',
    dbol_sides: 'Skutki uboczne',
    dbol_s1: 'Masywne zatrzymywanie wody: "moon face", obrzęki',
    dbol_s2: 'Ryzyko ginekomastii: wysoka aktywność estrogenowa',
    dbol_s3: 'Hepatotoksyczność: wątroba cierpi (17-alpha alkilowany)',
    dbol_s4: 'Ciśnienie krwi: znaczny wzrost',
    dbol_s5: 'Trądzik, tłusta skóra',
    dbol_doses: 'Typowe dawki',
    dbol_doses_text: '20-40 mg/dzień (beginners), 40-60 mg/dzień (advanced). Tani, ale brutalny dla wątroby.',
    marker_ast_alt: 'AST / ALT',
    marker_ast_alt_desc: 'Enzymy wątrobowe. Jeśli są podwyższone, twoja wątroba krzyczy o pomoc. Wszystkie steroidy doustne (Anavar, Dbol) wystrzeliwują je w górę.',
    marker_hdl_ldl: 'HDL / LDL',
    marker_hdl_ldl_desc: 'Cholesterol. PEDs brutalnie tłumią HDL (dobry) i podnoszą LDL (zły). Ryzyko zawału i udaru wykładniczo rośnie.',
    marker_hematocrit: 'Hematokryt',
    marker_hematocrit_desc: '% czerwonych krwinek we krwi. Testosteron go podnosi. Jeśli przekroczy 54%, krew jest jak syrop → zakrzepy, udar.',
    marker_lh_fsh: 'LH / FSH',
    marker_lh_fsh_desc: 'Hormony przysadki kontrolujące produkcję TST i plemników. Na cyklu spadają do zera. Jeśli nie wracają post-cycle = jesteś hipogonadyczny.',
    marker_e2: 'Estradiol (E2)',
    marker_e2_desc: 'Estrogen. Jeśli zbyt wysoki (z aromatyzacji TST) → gyno, zatrzymywanie wody. Jeśli zbyt niski (z przedawkowania AI) → połamane stawy, libido w dupie.',
    marker_prolactin: 'Prolaktyna',
    marker_prolactin_desc: 'Trenbolon i Nandrolon ją podnoszą. Wysoka prolaktyna = dysfunkcja erekcji, ginekomastia, "deca dick".',
    marker_creatinine: 'Kreatynina / GFR',
    marker_creatinine_desc: 'Funkcja nerek. Anaboliki je obciążają. Jeśli GFR spada, nerki odmawiają. Nieodwracalne uszkodzenie.',
    marker_tsh: 'TSH / T3 / T4',
    marker_tsh_desc: 'Tarczyca. PEDs mogą ją zaburzyć. Jeśli poza normą, metabolizm idzie w dupę, zmęczenie, depresja, przyrosty się kończą.',
    psych_god_title: '🚀 "God Mode" (Na Cyklu)',
    psych_god_1: 'Niezachwiana pewność siebie',
    psych_god_2: 'Zero lęku, agresja na siłowni jest zaletą',
    psych_god_3: 'Libido przez dach (jeśli estrogen w normie)',
    psych_god_4: 'Ekstremalna motywacja, "w dupie" zmęczenie',
    psych_god_5: 'Poczucie nieśmiertelności, dominacja we wszystkim',
    psych_hell_title: '💀 "Hormonal Hell" (Post-Cycle)',
    psych_hell_1: 'Depresja, lęki, zerowa motywacja',
    psych_hell_2: 'Libido w dupie, dysfunkcja erekcji',
    psych_hell_3: 'Bezsenność, drażliwość, emocjonalna labilność',
    psych_hell_4: 'Utrata wszystkich przyrostów (masa mięśniowa spada)',
    psych_hell_5: 'Poczucie bezwartościowości — "kim jestem bez roidów?"',
    psych_outro: 'Prawda jest brutalna: Na cyklu czujesz się jak bóg. Off cycle masz wrażenie, że umarł ci pies. Wielu uzależnia się właśnie przez ten psychologiczny whiplash. Blast & cruise (nieskończony cykl bez przerwy) staje się normą, bo PCT jest psychicznie nie do zniesienia.',
    detection_shoulders_title: '3D Delts (ramiona)',
    detection_shoulders_desc: 'Okrągłe, napompowane ramiona z ekstremalną separacją. Receptory androgenne w deltoidach reagują brutalnie na steroidy.',
    detection_flushing_title: 'Flushing & Trądzik',
    detection_flushing_desc: 'Czerwona twarz podczas treningu, trądzik na plecach i ramionach. Podwyższony puls + podwyższony hematokryt = permanentny "pump".',
    detection_gut_title: '"Roid Gut" (Palumboizm)',
    detection_gut_desc: 'Rozdęty brzuch pomimo niskiego tłuszczu. Wzrost narządów wewnętrznych z insuliny + HGH. Nowoczesna epidemia bodybuildingu.',
    detection_gains_title: 'Nierealne szybkie przyrosty',
    detection_gains_desc: 'Jeśli ktoś w 12 tygodni nabiera 15 kg masy mięśniowej i jednocześnie chudnie — nie, to nie kurczak z ryżem i brokuły.',
    detection_vascularity_title: 'Ekstremalna waskularyzacja',
    detection_vascularity_desc: 'Żyły jak węże nawet w spoczynku. Niski tłuszcz + zatrzymywanie wody w mięśniach + zwiększona objętość krwi = roadmap look.',
    detection_strength_title: 'Nadludzka siła przy niskiej wadze',
    detection_strength_desc: 'Bench 160 kg przy 80 kg wagi ciała i 8% tłuszczu? Anavar + Tren stack. Natural limit jest dużo niżej.',
    // New index.html translations
    nav_features: 'Funkcje',
    nav_thyroid: 'Tarczyca',
    nav_diets_toggle: 'Diety & nietolerancje ▾',
    nav_diets_mobile: 'Diety & nietolerancje',
    nav_diet_lactose: '🥛 Dieta bezlaktozowa',
    nav_diet_gluten: '🌾 Dieta bezglutenowa',
    nav_diet_histamine: '🧪 Nietolerancja histaminy',
    nav_diet_hashimoto: '🧬 Choroba Hashimoto',
    nav_ranks: 'Rangi',
    nav_story: 'Historia',
    nav_mobile_cta: 'Pobierz BOOOM za darmo →',
    hero_stat1_label: 'Sekcji appki',
    hero_stat2_label: 'Parametrów krwi',
    hero_stat3_label: 'AI Coach',
    story_tag: 'Historia założyciela',
    story_btn: 'Dlaczego powstał BOOOM? Moja historia.',
    feature_tag_ai_scan: 'AI skan',
    feature_tag_body_scan: 'Body scan',
    feature_tag_progress_pics: 'Zdjęcia postępów',
    feature_tag_trends: 'Trendy',
    feature_tag_exercises: 'Setki ćwiczeń',
    feature_tag_ai_plans: 'Plany AI',
    feature_tag_pr_tracking: 'PR tracking',
    feature_tag_timer: 'Timer',
    feature_tag_macros: 'Makra',
    feature_tag_calories: 'Kalorie',
    feature_tag_hydration: 'Nawodnienie',
    feature_tag_biohacking: 'Biohacking',
    feature_tag_36_params: '36 parametrów',
    feature_tag_time_trends: 'Trendy w czasie',
    feature_tag_alerts: 'Alarmy',
    feature_tag_247: '24/7 online',
    feature_tag_personalized: 'Spersonalizowany',
    feature_tag_blood_values: 'Wartości krwi',
    feature_tag_training_plans: 'Plany treningowe',
    feature_tag_challenges: 'Wyzwania',
    feature_tag_leaderboards: 'Rankingi',
    feature_tag_xp_ranks: 'XP & Rangi',
    feature_tag_feed: 'Feed',
    testimonials_tag: 'Społeczność',
    testimonials_title: 'Co mówią nasi harownicy',
    testimonials_subtitle: 'Prawdziwe historie. Prawdziwy postęp.',
    testimonials_rating: 'Ocenione przez użytkowników beta',
    testimonial1_text: '"W końcu appka, która rozumie, że fitness to nie tylko kalorie. Śledzenie wartości krwi otworzyło mi oczy — odkryłem, że mam niską ferrytynę i to był powód, dla którego stagnowałem rok. BOOOM dosłownie zmienił moje życie."',
    testimonial1_name: 'Marek Kováč',
    testimonial1_role: 'Powerlifter · Bratysława',
    testimonial2_text: '"Mam Hashimoto i przed BOOOM w ogóle nie wiedziałam, co mogę jeść i kiedy ćwiczyć. AI Coach wyjaśnił mi powiązania, których żaden trener ani lekarz nie powiedział mi w tak ludzki sposób. Teraz w końcu mam system."',
    testimonial2_name: 'Zuzana Horáková',
    testimonial2_role: 'Mama & Entuzjastka CrossFit · Żylina',
    testimonial3_text: '"Miałem 41 lat i myślałem, że stagnacja to wiek. GPS tracking, wartości krwi, plan AI — w 3 miesiące schudłem 9 kg jednocześnie przybierając mięśnie. To nie jest appka, to osobisty trener za cenę kawy."',
    testimonial3_name: 'Tomáš Novák',
    testimonial3_role: 'Cyklista & Ojciec trójki dzieci · Koszyce',
    fomo_badge: 'Ograniczony Early Access',
    fomo_title: 'BOOOM to nie appka dla ludzi,<br>którzy przychodzą na siłownię robić zdjęcia.',
    fomo_subtitle: 'Budujemy społeczność harowników, którzy chcą widzieć prawdziwe liczby, a nie tylko lajki. Pierwszych 500 profili ma priorytetowy dostęp do nowych funkcji na zawsze.',
    fomo_label: 'Aktualnie wolnych profili:',
    fomo_meta_taken: '27 profili zajętych',
    fomo_meta_free: '473 wolnych',
    fomo_cta: 'Zarejestruj się za darmo →',
    diets_tag: 'Zdrowie & Diety',
    diets_title: 'Więcej niż tylko fitness',
    diets_subtitle: 'Kompleksowe przewodniki dla osób ze specjalnymi potrzebami zdrowotnymi',
    teaser_thyroid_title: 'Co powinieneś wiedzieć o tarczycy',
    teaser_thyroid_desc: 'Niedoczynność, nadczynność, Hashimoto — objawy, dieta, suplementacja i najnowsze badania naukowe. Osobiste doświadczenie założyciela BOOOM.',
    teaser_lactose_title: 'Dieta bezlaktozowa — kompletny przewodnik',
    teaser_lactose_desc: 'Co jeść, czego unikać i jak nie stracić ważnych składników odżywczych. Kompletny przewodnik dla osób z nietolerancją laktozy.',
    teaser_gluten_title: 'Dieta bezglutenowa — dla celiaków',
    teaser_gluten_desc: 'Co jeść, co wykluczyć, gdzie kryje się gluten i jak nie stracić ważnych składników odżywczych. Kompletny przewodnik.',
    teaser_histamine_title: 'Nietolerancja histaminy',
    teaser_histamine_desc: 'Boli cię głowa po winie? Swędzi skóra po serze? Może to nie alergia. Kompletny przewodnik po nietolerancji histaminy.',
    teaser_hashimoto_title: 'Choroba Hashimoto — dieta i suplementacja',
    teaser_hashimoto_desc: 'Selen, myo-inozytol, dieta bezglutenowa i wszystko, co nauka mówi o leczeniu Hashimoto dietą. Osobiste doświadczenie założyciela BOOOM.',
    teaser_read_more: 'Czytaj więcej →',
    cta_tag: 'Zacznij dziś',
    cta_benefit1: 'Pełny dostęp za darmo',
    cta_benefit2: 'AI Coach od pierwszego dnia',
    cta_benefit3: 'Bez zobowiązań, anuluj w dowolnym momencie',
    cta_note: 'Setki osób z SK, CZ i PL już śledzą swoje postępy.',
    hero_scroll: 'Scroll',
    features_tag: 'Funkcje',
  },
  UK: {
    nav_tagline: 'TRAIN · TRACK · DOMINATE',
    nav_cta: 'Спробуй безкоштовно',
    hero_badge: '⚡ Фітнес-додаток нового покоління',
    hero_h1_line1: 'Тренуй.',
    hero_h1_line2: 'Стеж.',
    hero_h1_line3: 'Домінуй.',
    hero_subtitle: 'Перший фітнес-додаток, який справді тебе знає. Відстежуй прогрес, будуй звички та домінуй на кожному тренуванні.',
    hero_cta1: 'Почати безкоштовно',
    hero_cta2: 'Подивитись як це працює',
    badge1_title: '+12%',
    badge1_sub: "м'язова маса / 90 днів",
    badge2_title: 'Новий PR!',
    badge2_sub: 'жим лежачи 140 кг',
    badge3_title: 'AI Сканер',
    badge3_sub: 'Тіло проаналізовано',
    phone_cta: 'Скан тіла',
    hps_weight_label: 'Поточна вага',
    hps_weight_start: 'Старт: 65 кг',
    hps_weight_now: 'Зараз: 56.3 кг',
    fp_weight_label: 'Вага тіла',
    fp_weight_before: 'До: 79 кг',
    fp_weight_after: 'Зараз: 68.4 кг',
    fp_timer_label: 'Поточна вправа',
    fp_timer_set1: 'Підхід 1 — 80 кг × 8',
    fp_timer_set2: 'Підхід 2 — 85 кг × 6',
    fp_timer_set3: 'Підхід 3 — 90 кг × 5',
    fp_timer_cta: 'Завершити підхід',
    fp_macro_label: 'Сьогоднішній прийом',
    fp_blood_label: 'Показники крові',
    fp_blood_chol: 'Холестерин — високий',
    fp_blood_vitd: 'Вітамін D — норма',
    fp_supp_label: 'Сьогоднішні добавки',
    fp_supp_creatine: 'Креатин — 5 г',
    fp_supp_protein: 'Сироватка — 30 г',
    fp_supp_omega: 'Омега-3 — 2 г',
    fp_supp_vitd: 'Віт. D — 4000 IU',
    fp_cardio_label: 'Біг — зона 3',
    fp_cardio_pace: 'Темп 5:12/км',
    fp_cardio_hr: 'Пульс 158 bpm',
    stats_sections: 'розділів',
    stats_ranks: 'рангів',
    stats_motivation: 'мотивації',
    stats_price: 'старт',
    features_title: 'Все що тобі потрібно',
    features_subtitle: 'Повна фітнес-екосистема в одному додатку',
    features_p1_title: 'AI Сканер & Тіло',
    features_p1_desc: 'Сфотографуйся, і AI миттєво проаналізує склад твого тіла. Виміри, фото прогресу та точний трекер складу тіла в одному місці — побач зміну, яку вага ніколи не покаже.',
    features_p2_title: 'Тренувальний план & Hardcore Tracker',
    features_p2_desc: 'Сотні вправ, готові плани та AI-генеровані тренування саме для тебе. Таймер, паузи та відстеження PR — жодних припущень, лише цифри.',
    features_p3_title: 'Розумне харчування & Biohacking Macros',
    features_p3_desc: 'Стеж за калоріями, макросами та гідратацією на рівні біохакера. Їж розумніше, а не менше — і оптимізуй продуктивність зсередини.',
    features_h1_title: "Здоров'я & Показники крові",
    features_h1_desc: "36 показників крові — щитоподібна залоза, гормони, цукор, холестерин, печінка, вітаміни. Сфотографуй результати з паперу, і AI заповнить їх за 3 секунди.",
    features_h2_title: 'AI Coach BOOOMER',
    features_h2_desc: 'Твій особистий тренер онлайн 24/7. Знає твій профіль, показники крові, тренування та харчування. Радить максимально чесно і підлаштовує план за тебе.',
    features_h3_title: 'Спільнота & Motivation Feed',
    features_h3_desc: 'Виклики, рейтинги та стрічка прогресу спільноти. XP, значки та 6 рангів наближають тебе до титулу BOOOM Monster.',
    show_more_features_cta: 'Хочеш дізнатись, що ще вміє BOOOM?',
    features_modal_title: 'Ще більше функцій BOOOM',
    features_modal_close: 'Закрити',
    ranks_title: 'Твій шлях до вершини',
    ranks_subtitle: '6 рангів. Кожен крок веде тебе далі.',
    cta_title: 'Почни своє перше тренування сьогодні',
    cta_subtitle: 'Безкоштовно. Без кредитки. Без виправдань.',
    cta_button: 'Запустити BOOOM',
    footer_about: 'Про нас',
    footer_contact: 'Контакт',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms',
    footer_copy: '© 2026 BOOOM. Всі права захищені.',
    footer_founder: 'Laco, засновник BOOOM',
    footer_home: 'Головна',
    // Navigation
    nav_enhanced_fitness: 'За межами натуралу',
    // LAB (Ukrainian)
    lab_badge: 'RESTRICTED ACCESS',
    lab_teaser_title: 'BOOOM LAB: За межами натурального',
    lab_teaser_desc: 'Тестостерон. Тренболон. Анавар. Дiанабол. Брутально чесний deep-dive у світ enhanced fitness — механізми, побічні ефекти, показники крові та психологічна реальність.',
    lab_teaser_cta: 'Увійти в заборонену зону',
    lab_teaser_disclaimer: '⚠️ Тільки для освітніх цілей. BOOOM не підтримує і не пропагує використання анаболічних стероїдів.',
    nav_back: 'Назад на головну',
    lab_hero_badge: 'ОСВІТНІЙ КОНТЕНТ',
    lab_hero_title: 'BOOOM LAB: За межами натурального',
    lab_cta_title: 'Стеж за своїм здоров\'ям. Без відмовок.',
    lab_cta_desc: 'Чи ти natural, enhanced, або просто цікавий — BOOOM дає тобі комплексний моніторинг 36 показників крові, тренувань, харчування та твого прогресу.',
    lab_cta_button: 'Завантажити BOOOM безкоштовно',
    // Complete LAB page translations (Ukrainian)
    lab_hero_desc: 'Брутально чесний deep-dive у світ enhanced fitness. Без романтизації, без моралізування — лише факти, механізми, побічні ефекти та цифри, які ти повинен відстежувати, якщо вирішив піти цим шляхом.',
    lab_disclaimer_title: '⚠️ ВАЖЛИВЕ ПОПЕРЕДЖЕННЯ:',
    lab_disclaimer_text: 'Цей контент призначений виключно для освітніх цілей. BOOOM не підтримує, не пропагує і не заохочує використання анаболічних стероїдів. Будь-які рішення щодо здоров\'я та добавок повинні бути узгоджені з кваліфікованим лікарем.',
    substances_tag: 'ОСНОВНІ РЕЧОВИНИ',
    substances_title: 'Велика четвірка: Що тобі потрібно знати',
    substances_subtitle: 'Механізми дії, дозування, побічні ефекти та виявлення',
    markers_tag: 'МАРКЕРИ ЗДОРОВ\'Я',
    markers_title: '36 показників крові, які ти повинен відстежувати',
    markers_subtitle: 'Без моніторингу = російська рулетка з твоїм тілом',
    markers_intro: 'Якщо ти приймаєш PEDs і не відстежуєш показники крові, ти граєш з вогнем. Ось ключові маркери, які BOOOM відстежує, і чому вони критичні.',
    psych_tag: 'ПСИХОЛОГІЧНА РЕАЛЬНІСТЬ',
    psych_title: 'God Mode vs Hormonal Hell',
    psych_subtitle: 'Те, про що ніхто не каже: як PEDs впливають на твій розум',
    detection_tag: 'GYM LORE',
    detection_title: 'Як розпізнати, що хтось не natural?',
    detection_subtitle: 'Візуальні підказки, які не брешуть — жодних тестів не потрібно',
    chart_tst_title: 'Графік 1: Natural vs Enhanced — Рівні тестостерону',
    chart_tst_desc: 'Порівняння природних рівнів тестостерону з enhanced версією під час активного циклу',
    chart_tst_legend_natural: 'Природна продукція (чоловік 20-40 років)',
    chart_tst_legend_enhanced: 'Enhanced cycle (500 мг TST/тиждень)',
    chart_strength_title: 'Графік 2: Strength Rollercoaster — Цикл та краш',
    chart_strength_desc: 'Як виглядає сила під час циклу і після нього, якщо ти не робиш правильний PCT (Post Cycle Therapy)',
    chart_strength_legend_on: 'Тижні 0-12: Експоненційне зростання сили',
    chart_strength_legend_off: 'Тижні 12-20: Катастрофічний спад без PCT',
    // Substances (Ukrainian)
    tst_title: 'Тестостерон (TST)',
    tst_intro: 'Основа кожного циклу. Природний андрогенний гормон, який виробляє твоє тіло. Enhanced користувачі додають його екзогенно в дозах 5-10× вищих ніж природна продукція.',
    tst_mechanism: 'Як працює',
    tst_m1: 'Збільшує синтез білків у м\'язових клітинах',
    tst_m2: 'Пригнічує катаболізм (розпад м\'язів)',
    tst_m3: 'Збільшує ретенцію азоту та затримку води',
    tst_m4: 'Стимулює еритропоез (утворення червоних кров\'яних клітин)',
    tst_sides: 'Побічні ефекти',
    tst_s1: 'Ароматизація: конверсія в естроген → гінекомастія, затримка води',
    tst_s2: 'Пригнічення природної продукції: LH/FSH падає до нуля',
    tst_s3: 'Кардіоваскулярні: підвищений гематокрит, зростання кров\'яного тиску',
    tst_s4: 'Акне, облисіння (якщо генетично схильний)',
    tst_doses: 'Типові дози',
    tst_doses_text: '250-500 мг/тиждень (beginners), 500-750 мг/тиждень (intermediate), 750+ мг/тиждень (advanced risk zone)',
    tren_title: 'Тренболон (TREN)',
    tren_intro: '"Найсильніший стероїд на планеті." Спочатку призначений для худоби. Екстремально анаболічний та андрогенний. Дає величезні прирости, але платиш за це високу ціну.',
    tren_mechanism: 'Як працює',
    tren_m1: '5× більш анаболічний ніж тестостерон',
    tren_m2: 'Не конвертується в естроген, але зв\'язується з прогестероновими рецепторами',
    tren_m3: 'Драматично збільшує IGF-1 (інсуліноподібний фактор росту)',
    tren_m4: 'Інгібує кортизол (гормон стресу)',
    tren_sides: 'Побічні ефекти',
    tren_s1: 'Нічне потовиділення, безсоння: брутально порушений сон',
    tren_s2: '"Tren cough": напади кашлю після ін\'єкції',
    tren_s3: 'Кардіо дистопія: екстремально погіршена витривалість',
    tren_s4: 'Агресивність, тривога, параноя ("Tren rage")',
    tren_s5: 'Пригнічення лібідо пост-цикл (може тривати місяці)',
    tren_doses: 'Типові дози',
    tren_doses_text: '200-400 мг/тиждень (acetate form), 400-600 мг/тиждень (enanthate). Beginners повинні триматися подалі.',
    var_title: 'Анавар (Оксандролон)',
    var_intro: '"Жіночий стероїд." М\'який, але чистий. Не додає великих приростів, але дає суху, якісну м\'язову масу. Популярний у фазах катінгу.',
    var_mechanism: 'Як працює',
    var_m1: 'Оральний стероїд, похідна DHT',
    var_m2: 'Низький андрогенний ефект, мінімальна ароматизація',
    var_m3: 'Збільшує силу без значного приросту маси',
    var_m4: 'Підтримує спалювання жиру та васкулярність',
    var_sides: 'Побічні ефекти',
    var_s1: 'Гепатотоксичність: навантаження на печінку (AST/ALT ↑)',
    var_s2: 'Ліпідний профіль: зниження HDL, підвищення LDL',
    var_s3: 'Пригнічення природного TST (м\'якше ніж ін\'єкції)',
    var_s4: 'Відносно "безпечний" порівняно з іншими оральними, але все ще не цукерка',
    var_doses: 'Типові дози',
    var_doses_text: '20-50 мг/день (жінки), 50-80 мг/день (чоловіки), дорогий як чорт — часто підроблений',
    dbol_title: 'Дианабол (Метандростенолон)',
    dbol_intro: '"Dbol" — легенда золотої ери бодібілдингу. Масивні прирости за короткий час, але велика частина — вода. Kickstarter перших 4-6 тижнів циклу.',
    dbol_mechanism: 'Як працює',
    dbol_m1: 'Сильна анаболічна та андрогенна активність',
    dbol_m2: 'Виражена ароматизація в естроген',
    dbol_m3: 'Швидкий приріст сили та маси (5-10 кг за 4 тижні)',
    dbol_m4: 'Збільшує глікогеноліз та синтез білків',
    dbol_sides: 'Побічні ефекти',
    dbol_s1: 'Масивна затримка води: "moon face", набряки',
    dbol_s2: 'Ризик гінекомастії: висока естрогенова активність',
    dbol_s3: 'Гепатотоксичність: печінка страждає (17-альфа алкілований)',
    dbol_s4: 'Кров\'яний тиск: значне зростання',
    dbol_s5: 'Акне, жирна шкіра',
    dbol_doses: 'Типові дози',
    dbol_doses_text: '20-40 мг/день (beginners), 40-60 мг/день (advanced). Дешевий, але брутальний для печінки.',
    marker_ast_alt: 'AST / ALT',
    marker_ast_alt_desc: 'Печінкові ферменти. Якщо підвищені, твоя печінка кричить про допомогу. Всі оральні стероїди (Anavar, Dbol) вистрілюють їх вгору.',
    marker_hdl_ldl: 'HDL / LDL',
    marker_hdl_ldl_desc: 'Холестерин. PEDs брутально пригнічують HDL (хороший) і підвищують LDL (поганий). Ризик інфаркту та інсульту зростає експоненційно.',
    marker_hematocrit: 'Гематокрит',
    marker_hematocrit_desc: '% червоних кров\'яних клітин у крові. Тестостерон його підвищує. Якщо йде вище 54%, кров як сироп → тромби, інсульт.',
    marker_lh_fsh: 'LH / FSH',
    marker_lh_fsh_desc: 'Гормони гіпофіза, що контролюють продукцію TST та сперміїв. На циклі падають до нуля. Якщо не повертаються пост-цикл = ти гіпогонадний.',
    marker_e2: 'Естрадіол (E2)',
    marker_e2_desc: 'Естроген. Якщо надто високий (з ароматизації TST) → гіно, затримка води. Якщо надто низький (з передозування AI) → зламані суглоби, лібідо в дупі.',
    marker_prolactin: 'Пролактин',
    marker_prolactin_desc: 'Тренболон та Нандролон його підвищують. Високий пролактин = еректильна дисфункція, гінекомастія, "deca dick".',
    marker_creatinine: 'Креатинін / GFR',
    marker_creatinine_desc: 'Функція нирок. Анаболіки їх навантажують. Якщо GFR падає, нирки відмовляють. Незворотне ушкодження.',
    marker_tsh: 'TSH / T3 / T4',
    marker_tsh_desc: 'Щитоподібна залоза. PEDs можуть її порушити. Якщо поза нормою, метаболізм летить у дупу, втома, депресія, прирости закінчуються.',
    psych_god_title: '🚀 "God Mode" (На Циклі)',
    psych_god_1: 'Непохитна впевненість у собі',
    psych_god_2: 'Нуль тривоги, агресія в залі — перевага',
    psych_god_3: 'Лібідо через дах (якщо естроген у нормі)',
    psych_god_4: 'Екстремальна мотивація, "по хую" втома',
    psych_god_5: 'Відчуття безсмертя, домінування у всьому',
    psych_hell_title: '💀 "Hormonal Hell" (Пост-Цикл)',
    psych_hell_1: 'Депресія, тривога, нульова мотивація',
    psych_hell_2: 'Лібідо в дупі, еректильна дисфункція',
    psych_hell_3: 'Безсоння, дратівливість, емоційна лабільність',
    psych_hell_4: 'Втрата всіх приростів (м\'язова маса падає)',
    psych_hell_5: 'Відчуття непотрібності — "хто я без роїдів?"',
    psych_outro: 'Правда брутальна: На циклі ти почуваєшся як бог. Off cycle маєш відчуття, що в тебе помер пес. Багато хто стають залежними саме через цей психологічний whiplash. Blast & cruise (нескінченний цикл без паузи) стає нормою, бо PCT психічно нестерпний.',
    detection_shoulders_title: '3D Delts (плечі)',
    detection_shoulders_desc: 'Круглі, надуті плечі з екстремальною сепарацією. Андрогенні рецептори в дельтах реагують брутально на стероїди.',
    detection_flushing_title: 'Flushing & Акне',
    detection_flushing_desc: 'Червоне обличчя під час тренування, акне на спині та плечах. Підвищений пульс + підвищений гематокрит = перманентний "pump".',
    detection_gut_title: '"Roid Gut" (Палумбоізм)',
    detection_gut_desc: 'Роздутий живіт попри низький жир. Ріст внутрішніх органів з інсуліну + HGH. Сучасна епідемія бодібілдингу.',
    detection_gains_title: 'Нереально швидкі прирости',
    detection_gains_desc: 'Якщо хтось за 12 тижнів набирає 15 кг м\'язової маси і одночасно худне — ні, це не курка з рисом та броколі.',
    detection_vascularity_title: 'Екстремальна васкулярність',
    detection_vascularity_desc: 'Вени як шланги навіть у спокої. Низький жир + затримка води в м\'язах + збільшений об\'єм крові = roadmap look.',
    detection_strength_title: 'Надлюдська сила при низькій вазі',
    detection_strength_desc: 'Bench 160 кг при 80 кг вага тіла та 8% жиру? Anavar + Tren stack. Natural limit набагато нижче.',
    // New index.html translations
    nav_features: 'Функції',
    nav_thyroid: 'Щитовидна залоза',
    nav_diets_toggle: 'Дієти & непереносимість ▾',
    nav_diets_mobile: 'Дієти & непереносимість',
    nav_diet_lactose: '🥛 Безлактозна дієта',
    nav_diet_gluten: '🌾 Безглютенова дієта',
    nav_diet_histamine: '🧪 Гістамінова непереносимість',
    nav_diet_hashimoto: '🧬 Тиреоїдит Хашимото',
    nav_ranks: 'Ранги',
    nav_story: 'Історія',
    nav_mobile_cta: 'Завантажити BOOOM безкоштовно →',
    hero_stat1_label: 'Секцій appки',
    hero_stat2_label: 'Параметрів крові',
    hero_stat3_label: 'AI Coach',
    story_tag: 'Історія засновника',
    story_btn: 'Чому виник BOOOM? Моя історія.',
    feature_tag_ai_scan: 'AI скан',
    feature_tag_body_scan: 'Body scan',
    feature_tag_progress_pics: 'Фото прогресу',
    feature_tag_trends: 'Тренди',
    feature_tag_exercises: 'Сотні вправ',
    feature_tag_ai_plans: 'AI плани',
    feature_tag_pr_tracking: 'PR tracking',
    feature_tag_timer: 'Таймер',
    feature_tag_macros: 'Макро',
    feature_tag_calories: 'Калорії',
    feature_tag_hydration: 'Гідратація',
    feature_tag_biohacking: 'Biohacking',
    feature_tag_36_params: '36 параметрів',
    feature_tag_time_trends: 'Тренди в часі',
    feature_tag_alerts: 'Сповіщення',
    feature_tag_247: '24/7 онлайн',
    feature_tag_personalized: 'Персоналізований',
    feature_tag_blood_values: 'Показники крові',
    feature_tag_training_plans: 'Плани тренувань',
    feature_tag_challenges: 'Виклики',
    feature_tag_leaderboards: 'Рейтинги',
    feature_tag_xp_ranks: 'XP & Ранги',
    feature_tag_feed: 'Стрічка',
    testimonials_tag: 'Спільнота',
    testimonials_title: 'Що кажуть наші члени',
    testimonials_subtitle: 'Реальні історії. Реальний прогрес.',
    testimonials_rating: 'Оцінено бета-користувачами',
    testimonial1_text: '"Нарешті appка, яка розуміє, що фітнес — це не тільки калорії. Відстеження показників крові відкрило мені очі — я дізнався, що маю низький феритин, і це була причина, чому я стагнував рік. BOOOM буквально змінив моє життя."',
    testimonial1_name: 'Марек Ковач',
    testimonial1_role: 'Powerlifter · Братислава',
    testimonial2_text: '"У мене Хашимото, і до BOOOM я взагалі не знала, що можна їсти та коли тренуватися. AI Coach пояснив зв\'язки, які жоден тренер чи лікар не сказав мені так по-людськи. Тепер у мене нарешті є система."',
    testimonial2_name: 'Зузана Горакова',
    testimonial2_role: 'Мама & CrossFit ентузіастка · Жиліна',
    testimonial3_text: '"Мені було 41 рік, і я думав, що стагнація — це вік. GPS трекінг, показники крові, AI план — за 3 місяці я схуд 9 кг, водночас набравши м\'язів. Це не appка, це особистий тренер за ціною кави."',
    testimonial3_name: 'Томаш Новак',
    testimonial3_role: 'Велосипедист & Батько трьох дітей · Кошице',
    fomo_badge: 'Обмежений Early Access',
    fomo_title: 'BOOOM — це не appка для людей,<br>які приходять в зал робити фото.',
    fomo_subtitle: 'Ми будуємо спільноту працьовитих, які хочуть бачити реальні цифри, а не тільки лайки. Перші 500 профілів мають пріоритетний доступ до нових функцій назавжди.',
    fomo_label: 'Зараз вільних профілів:',
    fomo_meta_taken: '27 профілів зайнято',
    fomo_meta_free: '473 вільних',
    fomo_cta: 'Зареєструватися безкоштовно →',
    diets_tag: 'Здоров\'я & Дієти',
    diets_title: 'Більше ніж просто фітнес',
    diets_subtitle: 'Комплексні гіди для людей зі специфічними потребами здоров\'я',
    teaser_thyroid_title: 'Що потрібно знати про щитовидну залозу',
    teaser_thyroid_desc: 'Гіпотиреоз, гіпертиреоз, Хашимото — симптоми, дієта, добавки та найновіші наукові дослідження. Особистий досвід засновника BOOOM.',
    teaser_lactose_title: 'Безлактозна дієта — повний гід',
    teaser_lactose_desc: 'Що їсти, чого уникати і як не втратити важливі поживні речовини. Повний гід для людей з непереносимістю лактози.',
    teaser_gluten_title: 'Безглютенова дієта — для целіаків',
    teaser_gluten_desc: 'Що їсти, що виключити, де ховається глютен і як не втратити важливі поживні речовини. Повний гід.',
    teaser_histamine_title: 'Гістамінова непереносимість',
    teaser_histamine_desc: 'Болить голова після вина? Свербить шкіра після сиру? Можливо, це не алергія. Повний гід по гістаміновій непереносимості.',
    teaser_hashimoto_title: 'Тиреоїдит Хашимото — дієта і добавки',
    teaser_hashimoto_desc: 'Селен, міо-інозитол, безглютенова дієта і все, що наука каже про лікування Хашимото дієтою. Особистий досвід засновника BOOOM.',
    teaser_read_more: 'Читати далі →',
    cta_tag: 'Почни сьогодні',
    cta_benefit1: 'Повний доступ безкоштовно',
    cta_benefit2: 'AI Coach з першого дня',
    cta_benefit3: 'Без зобов\'язань, скасуй будь-коли',
    cta_note: 'Сотні людей з SK, CZ і PL вже відстежують свій прогрес.',
    hero_scroll: 'Scroll',
    features_tag: 'Функції',
  },
};

const pageTitles = {
  SK: 'BOOOM — Trénuj. Sleduj pokrok. Dominuj.',
  EN: 'BOOOM — Train. Track. Dominate.',
  CS: 'BOOOM — Trénuj. Sleduj pokrok. Dominuj.',
  PL: 'BOOOM — Trenuj. Śledź. Dominuj.',
  UK: 'BOOOM — Тренуй. Стеж. Домінуй.',
};

function setLanguage(lang) {
  if (!translations[lang]) return;

  const t = translations[lang];

  document.documentElement.setAttribute('lang', lang === 'UK' ? 'uk' : lang.toLowerCase());
  document.documentElement.setAttribute('data-lang', lang);

  document.querySelectorAll('[data-i18n]').forEach(function (el) {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      el.textContent = t[key];
    }
  });

  document.querySelectorAll('[data-i18n-aria]').forEach(function (el) {
    const key = el.getAttribute('data-i18n-aria');
    if (t[key] !== undefined) {
      el.setAttribute('aria-label', t[key]);
    }
  });

  document.querySelectorAll('.lang-btn').forEach(function (btn) {
    btn.classList.toggle('active', btn.textContent.trim() === lang);
  });

  document.title = pageTitles[lang] || pageTitles['SK'];

  try {
    localStorage.setItem('booom_lang', lang);
  } catch (e) {}
}

(function () {
  var saved;
  try { saved = localStorage.getItem('booom_lang'); } catch (e) {}
  setLanguage(saved && translations[saved] ? saved : 'SK');
}());
